// Generado por bin/generar.php a partir de catalogo/permisos.json (versión 1.7.0).
// No editar a mano: cambiar el JSON y volver a generar.

package permisos

import (
	"context"
	"database/sql"
	"strings"
)

// SQLEsquema crea las tablas de roles y permisos si no existen (sql/esquema.sql).
const SQLEsquema = `-- Tablas de roles y permisos de la PIN (MySQL). Idempotente: se puede correr
-- en cada deploy; si una tabla ya existe no la toca.
--
-- Va antes de sincronizar.sql. Lo puede correr cualquier consumidor (backend-pin
-- con app:permissions:sync, backend-go con permisos.Sincronizar o mysql a mano).

CREATE TABLE IF NOT EXISTS permissions (
    id INT AUTO_INCREMENT NOT NULL,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(40) NOT NULL,
    active TINYINT(1) DEFAULT 1 NOT NULL,
    ` + "`" + `order` + "`" + ` INT DEFAULT 0 NOT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    UNIQUE INDEX uniq_permissions_slug (slug),
    INDEX idx_permissions_type (type),
    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE ` + "`" + `utf8mb4_unicode_ci` + "`" + ` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT NOT NULL,
    slug VARCHAR(60) NOT NULL,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    legacy_role VARCHAR(60) DEFAULT NULL,
    ` + "`" + `system` + "`" + ` VARCHAR(20) DEFAULT 'pin' NOT NULL,
    active TINYINT(1) DEFAULT 1 NOT NULL,
    ` + "`" + `order` + "`" + ` INT DEFAULT 0 NOT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    UNIQUE INDEX uniq_roles_slug (slug),
    INDEX idx_roles_system (` + "`" + `system` + "`" + `),
    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE ` + "`" + `utf8mb4_unicode_ci` + "`" + ` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS role_has_permissions (
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    INDEX idx_rhp_permission (permission_id),
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rhp_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_rhp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE ` + "`" + `utf8mb4_unicode_ci` + "`" + ` ENGINE = InnoDB;

-- Sin CASCADE en el rol: borrar un rol asignado tiene que fallar.
CREATE TABLE IF NOT EXISTS model_has_roles (
    role_id INT NOT NULL,
    model_type VARCHAR(40) NOT NULL,
    model_id INT NOT NULL,
    INDEX idx_mhr_model (model_type, model_id),
    PRIMARY KEY (role_id, model_type, model_id),
    CONSTRAINT fk_mhr_role FOREIGN KEY (role_id) REFERENCES roles (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE ` + "`" + `utf8mb4_unicode_ci` + "`" + ` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS model_has_permissions (
    permission_id INT NOT NULL,
    model_type VARCHAR(40) NOT NULL,
    model_id INT NOT NULL,
    INDEX idx_mhp_model (model_type, model_id),
    PRIMARY KEY (permission_id, model_type, model_id),
    CONSTRAINT fk_mhp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE ` + "`" + `utf8mb4_unicode_ci` + "`" + ` ENGINE = InnoDB;
`

// SQLSincronizar sincroniza roles y permisos con el catálogo (sql/sincronizar.sql).
const SQLSincronizar = `-- Generado por bin/generar.php a partir de catalogo/permisos.json (versión 1.7.0).
-- No editar a mano: cambiar el JSON y volver a generar.
--
-- Sincroniza roles y permisos con el catálogo. Idempotente; va después de
-- esquema.sql. Nunca borra nada y no pisa lo que se administra desde gestion:
--   - roles: crea los que faltan; uno existente no se toca.
--   - permisos nuevos: se insertan y se asignan a sus roles iniciales (solo esa vez).
--   - permisos existentes: solo type y active. name y order se editan en gestion.
--   - permisos que ya no están en el catálogo: active = 0.
-- Al final devuelve una fila con lo que hizo.

START TRANSACTION;

DROP TEMPORARY TABLE IF EXISTS pin_permisos_roles;
CREATE TEMPORARY TABLE pin_permisos_roles (
    slug VARCHAR(60) NOT NULL PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    ` + "`" + `system` + "`" + ` VARCHAR(20) NOT NULL,
    ` + "`" + `order` + "`" + ` INT NOT NULL,
    legacy_role VARCHAR(60) NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO pin_permisos_roles (slug, name, ` + "`" + `system` + "`" + `, ` + "`" + `order` + "`" + `, legacy_role) VALUES
    ('sales', 'Vendedor', 'pin', 0, 'ROLE_VENTAS'),
    ('account_manager', 'Responsable de cuenta', 'pin', 2, 'ROLE_RESPCU'),
    ('konnen', 'Vendedor Konnen', 'pin', 3, 'ROLE_KONNEN'),
    ('finance', 'Finanzas', 'pin', 4, 'ROLE_FINANZAS'),
    ('manager', 'Gerente', 'pin', 5, 'ROLE_GERENTE'),
    ('accounts_payable', 'Cuentas a pagar', 'pin', 10, 'ROLE_CUENTAS_A_PAGAR'),
    ('super_admin', 'Super admin', 'pin', 11, 'ROLE_SUPER_ADMIN'),
    ('developer', 'Desarrollador', 'pin', 12, 'ROLE_DEVELOPER'),
    ('client', 'Empresa', 'pin', 14, 'ROLE_EMPRESA'),
    ('supplier', 'Proveedor', 'pin', 16, 'ROLE_PROVEEDOR'),
    ('gestion_planning', 'Planeamiento', 'gestion', 19, NULL),
    ('gestion_content', 'Contenidos', 'gestion', 20, NULL),
    ('gestion_accounts_payable', 'Cuentas a pagar', 'gestion', 21, NULL),
    ('gestion_admin', 'Administrador de gestión', 'gestion', 22, NULL),
    ('gestion_accounting_tax', 'Contabilidad e impuestos', 'gestion', 23, NULL);

DROP TEMPORARY TABLE IF EXISTS pin_permisos_catalogo;
CREATE TEMPORARY TABLE pin_permisos_catalogo (
    slug VARCHAR(80) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(40) NOT NULL,
    ` + "`" + `order` + "`" + ` INT NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO pin_permisos_catalogo (slug, name, type, ` + "`" + `order` + "`" + `) VALUES
    ('pin.ingresar', 'Ingresar a la PIN', 'pin', 0),
    ('mi_cuenta.ingresar', 'Mi cuenta', 'pin', 1),
    ('mis_gestiones.ingresar', 'Mis gestiones', 'pin', 2),
    ('cliente.elegir_obligatorio', 'Elegir cliente antes de operar', 'pin', 3),
    ('chat_ayuda.ver', 'Ver botones de chat', 'pin', 4),
    ('encuesta.responder', 'Encuesta de satisfacción', 'pin', 5),
    ('cliente.operar_como', 'Operar en nombre de un cliente', 'pin', 6),
    ('catalogo.ver_como_vendedor', 'Catálogo con condiciones de vendedor', 'pin', 7),
    ('cliente.dar_de_alta', 'Dar de alta clientes', 'pin', 8),
    ('cliente.ver_informacion_interna', 'Ver información interna del cliente', 'pin', 9),
    ('cliente.ver_notas', 'Ver notas del cliente', 'pin', 10),
    ('vendedor.id_sap', 'Vendedor Famiq con ID SAP', 'pin', 11),
    ('productos_especiales.ver', 'Ver Productos Especiales', 'pin', 12),
    ('precio.ver_standard', 'Ver precio standard', 'pin', 13),
    ('producto.ver_marcas_internas', 'Ver marcas internas del producto', 'pin', 14),
    ('producto.ver_descuento_maximo', 'Ver descuento máximo y contrato marco', 'pin', 15),
    ('stock.ver_por_sucursal', 'Ver stock por sucursal', 'pin', 16),
    ('catalogo.ver_datos_tecnicos', 'Ver datos técnicos internos', 'pin', 17),
    ('recortes.ver_deposito_origen', 'Ver depósito de origen en recortes', 'pin', 18),
    ('politica_precios.descargar', 'Descargar política de precios', 'pin', 19),
    ('producto.ver_precio_sin_descuento', 'Ver precio sin descuento por presentación', 'pin', 20),
    ('catalogo.ver_como_comprar', 'Ver cómo comprar', 'pin', 21),
    ('listas.usar', 'Usar listas y favoritos', 'pin', 22),
    ('listas.crear_famiq', 'Crear listas Famiq', 'pin', 23),
    ('listas.editar_famiq', 'Editar listas Famiq', 'pin', 24),
    ('listas.descargar_reporte', 'Descargar reporte de listas', 'pin', 25),
    ('carrito.precio_manual', 'Precio manual y moneda', 'pin', 26),
    ('carrito.notas', 'Notas en el carrito', 'pin', 27),
    ('carrito.alternativas', 'Alternativas de producto', 'pin', 28),
    ('carrito.opciones_cabecera', 'Opciones del carrito', 'pin', 29),
    ('carrito.carga_masiva_oferta_precio_manual', 'Carga masiva en ofertas de precio manual', 'pin', 30),
    ('carrito.cambiar_centro', 'Cambiar el centro de las posiciones', 'pin', 31),
    ('carrito.anular_con_motivo', 'Anular posición con motivo', 'pin', 32),
    ('carrito.vendedor_referenciado', 'Vendedor referenciado', 'pin', 33),
    ('carrito.vendedor_referenciado_kiosco', 'Vendedor referenciado desde kiosco', 'pin', 34),
    ('carrito.recuperar_sin_forzar_centro', 'Recuperar carrito sin forzar centro', 'pin', 35),
    ('cupones.usar', 'Cupones', 'pin', 36),
    ('envio.bonificar', 'Bonificar envío y embalaje', 'pin', 37),
    ('carrito.agregar', 'Agregar productos al carrito', 'pin', 38),
    ('cotizacion.guardar_en_cualquier_paso', 'Guardar cotización en cualquier paso', 'pin', 39),
    ('cotizacion.crear', 'Crear ofertas comunes', 'pin', 40),
    ('cotizacion.crear_especial', 'Crear ofertas especiales', 'pin', 41),
    ('pedido.emitir', 'Emitir pedidos', 'pin', 42),
    ('pedido.exigir_mail_confirmacion', 'Exigir mail de confirmación', 'pin', 43),
    ('pedido.finalidad', 'Finalidad del pedido', 'pin', 44),
    ('pedido.consignacion', 'Consignación', 'pin', 45),
    ('pedido.pago_mostrador', 'Pago en mostrador', 'pin', 46),
    ('pedido.ofrecer_retiro_mostrador', 'Ofrecer retiro en mostrador', 'pin', 47),
    ('pago.condiciones_adicionales', 'Condiciones de pago adicionales', 'pin', 48),
    ('pago.cambiar_moneda', 'Cambiar moneda de pago', 'pin', 49),
    ('pedido.ver_muestras_gratis', 'Ver pedidos de muestra gratis', 'pin', 50),
    ('pedido.ver_aviso_pago', 'Ver avisos de pago al cliente', 'pin', 51),
    ('documento.elegir_posiciones', 'Elegir posiciones de una cotización', 'pin', 52),
    ('documento.copiar_cotizacion', 'Copiar cotización', 'pin', 53),
    ('documento.actualizar_oferta_especial', 'Actualizar oferta especial vencida', 'pin', 54),
    ('documento.omitir_control_centro', 'Abrir documentos de otro centro', 'pin', 55),
    ('documento.ver_condiciones_internas', 'Ver condiciones internas', 'pin', 56),
    ('mi_cuenta.compras', 'Compras y transacciones', 'pin', 57),
    ('mi_cuenta.ventas', 'Ventas', 'pin', 58),
    ('mi_cuenta.ayuda', 'Ayuda', 'pin', 59),
    ('mi_cuenta.centro_ayuda', 'Centro de ayuda', 'pin', 60),
    ('mi_cuenta.estado_cuenta', 'Estado de cuenta', 'pin', 61),
    ('mi_cuenta.legajo_impositivo', 'Legajo impositivo', 'pin', 62),
    ('mi_cuenta.mis_codigos', 'Mis códigos', 'pin', 63),
    ('mi_cuenta.direcciones', 'Mis direcciones', 'pin', 64),
    ('mi_cuenta.cambiar_contrasena', 'Cambiar contraseña', 'pin', 65),
    ('personas.gestionar', 'Mis personas', 'pin', 66),
    ('personas.favoritas', 'Personas favoritas', 'pin', 67),
    ('comprobantes_pago.ver', 'Comprobantes de pago', 'pin', 68),
    ('reclamos.modo_asesor', 'Reclamos en modo asesor', 'pin', 69),
    ('reclamos.notas_internas', 'Notas internas en reclamos', 'pin', 70),
    ('crm.gestionar_contactos', 'Gestionar contactos del CRM', 'pin', 71),
    ('konnen.busqueda', 'Búsqueda Konnen', 'pin', 72),
    ('konnen.documentos', 'Documentos Konnen', 'pin', 73),
    ('cuenta_cliente.usar', 'Cuenta cliente', 'pin', 74),
    ('cuenta_proveedor.usar', 'Cuenta proveedor', 'pin', 75),
    ('proveedores.portal', 'Portal de proveedores', 'pin', 76),
    ('proveedor.operar_como', 'Operar en nombre de un proveedor', 'pin', 77),
    ('pedidos_bloqueados.filtrar_por_asesor', 'Filtrar pedidos bloqueados por asesor', 'pin', 78),
    ('transportes.ver_horarios', 'Ver horarios de transportes', 'pin', 79),
    ('transportes.crear', 'Crear transportes', 'pin', 80),
    ('sistema.log_sap', 'Registro técnico de SAP', 'pin', 81),
    ('sistema.debug_carrito', 'Debug del carrito', 'pin', 82),
    ('sistema.marcas_desarrollo', 'Marcas de desarrollo en pantalla', 'pin', 83),
    ('sistema.no_informar_usuario_sap', 'No informar el usuario a SAP', 'pin', 84),
    ('totem.generar_ticket', 'Generar ticket del tótem', 'pin', 85),
    ('totem.ver_tickets_en_espera', 'Ver tickets en espera del tótem', 'pin', 86),
    ('producto.mantenimiento', 'Mantenimiento de productos', 'pin', 87),
    ('gestion.ingresar', 'Ingresar a gestión', 'gestion', 88),
    ('roles.administrar', 'Administrar roles y permisos', 'gestion', 89),
    ('usuarios.administrar_internos', 'Administrar usuarios internos', 'gestion', 90),
    ('user.index', 'Ver usuarios', 'gestion', 91),
    ('user.create', 'Crear usuario', 'gestion', 92),
    ('user.edit', 'Editar usuario', 'gestion', 93),
    ('user.delete', 'Eliminar usuario', 'gestion', 94),
    ('product.index', 'Ver Productos', 'gestion', 95),
    ('payment.index', 'Ver Pagos', 'gestion', 96),
    ('client-code.index', 'Ver Código Cliente', 'gestion', 97),
    ('client-code.create', 'Crear Código Cliente', 'gestion', 98),
    ('client-code.destroy', 'Eliminar Código Cliente', 'gestion', 99),
    ('list.index', 'Ver Mis Listas', 'gestion', 100),
    ('list.show', 'Listas de Empresa', 'gestion', 101),
    ('list.create', 'Crear Mis Listas', 'gestion', 102),
    ('list.destroy', 'Eliminar Lista', 'gestion', 103),
    ('legajo.index', 'Ver Legajo impositivo', 'gestion', 104),
    ('legajo.update', 'Editar Legajo impositivo', 'gestion', 105),
    ('materials.index', 'Ver Materiales con Defectos', 'gestion', 106),
    ('materials.show', 'Ver Material con Defecto', 'gestion', 107),
    ('materials.create', 'Crear Material con Defecto', 'gestion', 108),
    ('materials.destroy', 'Eliminar Material con Defecto', 'gestion', 109),
    ('lead.index', 'Ver Leads', 'gestion', 110),
    ('tag.index', 'Ver Etiquetas', 'gestion', 111),
    ('tag.create', 'Crear Etiquetas', 'gestion', 112),
    ('tag.edit', 'Editar Etiqueta', 'gestion', 113),
    ('tag.destroy', 'Eliminar Etiqueta', 'gestion', 114),
    ('filter-order.index', 'Ver Filtros', 'gestion', 115),
    ('filter-order.show', 'Ver Ordenamiento de filtros', 'gestion', 116),
    ('filter-order.update', 'Editar Ordenamiento de filtros', 'gestion', 117),
    ('component-types.types', 'Ver Tipos de componentes', 'gestion', 118),
    ('component-types.index', 'Ver Componentes de la Sección', 'gestion', 119),
    ('components.index', 'Ver Componentes', 'gestion', 120),
    ('components.create', 'Crear Componente', 'gestion', 121),
    ('components.component.edit', 'Editar Componente', 'gestion', 122),
    ('components.component.delete', 'Eliminar Componente', 'gestion', 123),
    ('logos.index', 'Ver Logos', 'gestion', 124),
    ('logos.create', 'Crear Logo', 'gestion', 125),
    ('logos.logo.edit', 'Editar Logo', 'gestion', 126),
    ('logos.logo.delete', 'Eliminar Logo', 'gestion', 127),
    ('hierarchy-node.index', 'Ver Nodos', 'gestion', 128),
    ('hierarchy-node.create', 'Crear Nodo', 'gestion', 129),
    ('hierarchy-node.node.edit', 'Editar Nodo', 'gestion', 130),
    ('hierarchy-node.node.delete', 'Eliminar Nodo', 'gestion', 131),
    ('team.index', 'Ver Personal', 'gestion', 132),
    ('team.create', 'Crear Personal', 'gestion', 133),
    ('team.edit', 'Editar Personal', 'gestion', 134),
    ('team.delete', 'Eliminar Personal', 'gestion', 135),
    ('messages.index', 'Ver Mensajes', 'gestion', 136),
    ('messages.create', 'Crear Mensajes', 'gestion', 137),
    ('messages.message.edit', 'Editar Mensajes', 'gestion', 138),
    ('messages.message.delete', 'Eliminar Mensajes', 'gestion', 139),
    ('notifications.index', 'Ver Novedad', 'gestion', 140),
    ('notifications.create', 'Crear Novedad', 'gestion', 141),
    ('notifications.notification.edit', 'Editar Novedad', 'gestion', 142),
    ('notifications.notification.delete', 'Eliminar Novedad', 'gestion', 143),
    ('feature-flags.index', 'Ver Funcionalidades', 'gestion', 144),
    ('feature-flags.create', 'Crear funcionalidad', 'gestion', 145),
    ('feature-flags.feature-flag.edit', 'Editar Funcionalidades', 'gestion', 146),
    ('feature-flags.feature-flag.delete', 'Eliminar Funcionalidades', 'gestion', 147),
    ('certificacion.index', 'Ver Certificación', 'gestion', 148),
    ('certificacion.update', 'Editar Certificación', 'gestion', 149),
    ('calidad.index', 'Ver Política de calidad', 'gestion', 150),
    ('calidad.update', 'Editar Política de calidad', 'gestion', 151),
    ('segments.index', 'Ver Segmentos', 'gestion', 152),
    ('segments.create', 'Crear Segmento', 'gestion', 153),
    ('segments.segment.edit', 'Editar Segmento', 'gestion', 154),
    ('segments.segment.delete', 'Eliminar Segmento', 'gestion', 155),
    ('empresas.index', 'Ver Empresas', 'gestion', 156),
    ('header-links.index', 'Ver Links del header', 'gestion', 157),
    ('header-links.create', 'Crear Links del header', 'gestion', 158),
    ('header-links.link.edit', 'Editar Links del header', 'gestion', 159),
    ('header-links.link.delete', 'Eliminar Links del header', 'gestion', 160),
    ('info.library.index', 'Ver Biblioteca', 'gestion', 161),
    ('info.library.collections.index', 'Ver Colecciones', 'gestion', 162),
    ('info.library.collections.create', 'Crear Colección', 'gestion', 163),
    ('info.library.collections.collection.edit', 'Editar Colección', 'gestion', 164),
    ('info.library.collections.collection.delete', 'Eliminar Colección', 'gestion', 165),
    ('info.library.articles.index', 'Ver Artículos', 'gestion', 166),
    ('info.library.articles.create', 'Crear Artículo', 'gestion', 167),
    ('info.library.articles.article.edit', 'Editar Artículo', 'gestion', 168),
    ('info.library.articles.article.delete', 'Eliminar Artículo', 'gestion', 169),
    ('info.facts.index', 'Ver ¿Sabías qué?', 'gestion', 170),
    ('info.facts.create', 'Crear dato', 'gestion', 171),
    ('info.facts.fact.edit', 'Editar dato', 'gestion', 172),
    ('info.facts.fact.delete', 'Eliminar dato', 'gestion', 173),
    ('footer.index', 'Ver Footer', 'gestion', 174),
    ('footer.edit', 'Editar Footer', 'gestion', 175);

DROP TEMPORARY TABLE IF EXISTS pin_permisos_iniciales;
CREATE TEMPORARY TABLE pin_permisos_iniciales (
    permiso VARCHAR(80) NOT NULL,
    rol VARCHAR(60) NOT NULL,
    PRIMARY KEY (permiso, rol)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO pin_permisos_iniciales (permiso, rol) VALUES
    ('pin.ingresar', 'sales'),
    ('pin.ingresar', 'account_manager'),
    ('pin.ingresar', 'konnen'),
    ('pin.ingresar', 'finance'),
    ('pin.ingresar', 'manager'),
    ('pin.ingresar', 'accounts_payable'),
    ('pin.ingresar', 'super_admin'),
    ('pin.ingresar', 'developer'),
    ('pin.ingresar', 'client'),
    ('pin.ingresar', 'supplier'),
    ('mi_cuenta.ingresar', 'sales'),
    ('mi_cuenta.ingresar', 'account_manager'),
    ('mi_cuenta.ingresar', 'konnen'),
    ('mi_cuenta.ingresar', 'finance'),
    ('mi_cuenta.ingresar', 'manager'),
    ('mi_cuenta.ingresar', 'accounts_payable'),
    ('mi_cuenta.ingresar', 'super_admin'),
    ('mi_cuenta.ingresar', 'developer'),
    ('mi_cuenta.ingresar', 'client'),
    ('mi_cuenta.ingresar', 'supplier'),
    ('mis_gestiones.ingresar', 'sales'),
    ('mis_gestiones.ingresar', 'account_manager'),
    ('mis_gestiones.ingresar', 'konnen'),
    ('mis_gestiones.ingresar', 'manager'),
    ('mis_gestiones.ingresar', 'accounts_payable'),
    ('mis_gestiones.ingresar', 'super_admin'),
    ('mis_gestiones.ingresar', 'developer'),
    ('cliente.elegir_obligatorio', 'sales'),
    ('cliente.elegir_obligatorio', 'account_manager'),
    ('cliente.elegir_obligatorio', 'konnen'),
    ('cliente.elegir_obligatorio', 'finance'),
    ('cliente.elegir_obligatorio', 'manager'),
    ('cliente.elegir_obligatorio', 'super_admin'),
    ('cliente.elegir_obligatorio', 'developer'),
    ('chat_ayuda.ver', 'sales'),
    ('chat_ayuda.ver', 'account_manager'),
    ('chat_ayuda.ver', 'konnen'),
    ('chat_ayuda.ver', 'finance'),
    ('chat_ayuda.ver', 'manager'),
    ('chat_ayuda.ver', 'super_admin'),
    ('chat_ayuda.ver', 'developer'),
    ('chat_ayuda.ver', 'client'),
    ('encuesta.responder', 'client'),
    ('cliente.operar_como', 'sales'),
    ('cliente.operar_como', 'account_manager'),
    ('cliente.operar_como', 'manager'),
    ('cliente.operar_como', 'super_admin'),
    ('cliente.operar_como', 'developer'),
    ('catalogo.ver_como_vendedor', 'sales'),
    ('catalogo.ver_como_vendedor', 'account_manager'),
    ('catalogo.ver_como_vendedor', 'manager'),
    ('catalogo.ver_como_vendedor', 'super_admin'),
    ('catalogo.ver_como_vendedor', 'developer'),
    ('cliente.dar_de_alta', 'sales'),
    ('cliente.dar_de_alta', 'account_manager'),
    ('cliente.dar_de_alta', 'manager'),
    ('cliente.dar_de_alta', 'super_admin'),
    ('cliente.dar_de_alta', 'developer'),
    ('cliente.ver_informacion_interna', 'sales'),
    ('cliente.ver_informacion_interna', 'account_manager'),
    ('cliente.ver_informacion_interna', 'konnen'),
    ('cliente.ver_informacion_interna', 'manager'),
    ('cliente.ver_informacion_interna', 'super_admin'),
    ('cliente.ver_informacion_interna', 'developer'),
    ('cliente.ver_notas', 'sales'),
    ('cliente.ver_notas', 'account_manager'),
    ('cliente.ver_notas', 'manager'),
    ('cliente.ver_notas', 'super_admin'),
    ('cliente.ver_notas', 'developer'),
    ('vendedor.id_sap', 'sales'),
    ('vendedor.id_sap', 'account_manager'),
    ('productos_especiales.ver', 'sales'),
    ('productos_especiales.ver', 'account_manager'),
    ('productos_especiales.ver', 'manager'),
    ('productos_especiales.ver', 'super_admin'),
    ('productos_especiales.ver', 'developer'),
    ('precio.ver_standard', 'sales'),
    ('precio.ver_standard', 'account_manager'),
    ('precio.ver_standard', 'manager'),
    ('precio.ver_standard', 'super_admin'),
    ('precio.ver_standard', 'developer'),
    ('producto.ver_marcas_internas', 'sales'),
    ('producto.ver_marcas_internas', 'account_manager'),
    ('producto.ver_marcas_internas', 'konnen'),
    ('producto.ver_marcas_internas', 'manager'),
    ('producto.ver_marcas_internas', 'super_admin'),
    ('producto.ver_marcas_internas', 'developer'),
    ('producto.ver_descuento_maximo', 'sales'),
    ('producto.ver_descuento_maximo', 'account_manager'),
    ('producto.ver_descuento_maximo', 'konnen'),
    ('producto.ver_descuento_maximo', 'manager'),
    ('producto.ver_descuento_maximo', 'super_admin'),
    ('producto.ver_descuento_maximo', 'developer'),
    ('stock.ver_por_sucursal', 'sales'),
    ('stock.ver_por_sucursal', 'account_manager'),
    ('stock.ver_por_sucursal', 'konnen'),
    ('stock.ver_por_sucursal', 'manager'),
    ('stock.ver_por_sucursal', 'super_admin'),
    ('stock.ver_por_sucursal', 'developer'),
    ('catalogo.ver_datos_tecnicos', 'super_admin'),
    ('catalogo.ver_datos_tecnicos', 'developer'),
    ('recortes.ver_deposito_origen', 'sales'),
    ('recortes.ver_deposito_origen', 'account_manager'),
    ('recortes.ver_deposito_origen', 'konnen'),
    ('recortes.ver_deposito_origen', 'finance'),
    ('recortes.ver_deposito_origen', 'manager'),
    ('recortes.ver_deposito_origen', 'super_admin'),
    ('recortes.ver_deposito_origen', 'developer'),
    ('recortes.ver_deposito_origen', 'client'),
    ('politica_precios.descargar', 'sales'),
    ('politica_precios.descargar', 'account_manager'),
    ('politica_precios.descargar', 'finance'),
    ('politica_precios.descargar', 'manager'),
    ('politica_precios.descargar', 'accounts_payable'),
    ('politica_precios.descargar', 'super_admin'),
    ('politica_precios.descargar', 'developer'),
    ('politica_precios.descargar', 'client'),
    ('politica_precios.descargar', 'supplier'),
    ('producto.ver_precio_sin_descuento', 'sales'),
    ('producto.ver_precio_sin_descuento', 'account_manager'),
    ('producto.ver_precio_sin_descuento', 'finance'),
    ('producto.ver_precio_sin_descuento', 'manager'),
    ('producto.ver_precio_sin_descuento', 'accounts_payable'),
    ('producto.ver_precio_sin_descuento', 'super_admin'),
    ('producto.ver_precio_sin_descuento', 'developer'),
    ('producto.ver_precio_sin_descuento', 'client'),
    ('producto.ver_precio_sin_descuento', 'supplier'),
    ('catalogo.ver_como_comprar', 'sales'),
    ('catalogo.ver_como_comprar', 'account_manager'),
    ('catalogo.ver_como_comprar', 'finance'),
    ('catalogo.ver_como_comprar', 'manager'),
    ('catalogo.ver_como_comprar', 'accounts_payable'),
    ('catalogo.ver_como_comprar', 'super_admin'),
    ('catalogo.ver_como_comprar', 'developer'),
    ('catalogo.ver_como_comprar', 'client'),
    ('catalogo.ver_como_comprar', 'supplier'),
    ('listas.usar', 'sales'),
    ('listas.usar', 'account_manager'),
    ('listas.usar', 'manager'),
    ('listas.usar', 'super_admin'),
    ('listas.usar', 'developer'),
    ('listas.usar', 'client'),
    ('listas.crear_famiq', 'sales'),
    ('listas.crear_famiq', 'account_manager'),
    ('listas.crear_famiq', 'manager'),
    ('listas.crear_famiq', 'super_admin'),
    ('listas.crear_famiq', 'developer'),
    ('listas.editar_famiq', 'super_admin'),
    ('listas.descargar_reporte', 'super_admin'),
    ('listas.descargar_reporte', 'developer'),
    ('carrito.precio_manual', 'sales'),
    ('carrito.precio_manual', 'account_manager'),
    ('carrito.precio_manual', 'konnen'),
    ('carrito.precio_manual', 'manager'),
    ('carrito.precio_manual', 'super_admin'),
    ('carrito.precio_manual', 'developer'),
    ('carrito.notas', 'sales'),
    ('carrito.notas', 'account_manager'),
    ('carrito.notas', 'konnen'),
    ('carrito.notas', 'manager'),
    ('carrito.notas', 'super_admin'),
    ('carrito.notas', 'developer'),
    ('carrito.alternativas', 'sales'),
    ('carrito.alternativas', 'account_manager'),
    ('carrito.alternativas', 'konnen'),
    ('carrito.alternativas', 'manager'),
    ('carrito.alternativas', 'super_admin'),
    ('carrito.alternativas', 'developer'),
    ('carrito.opciones_cabecera', 'sales'),
    ('carrito.opciones_cabecera', 'account_manager'),
    ('carrito.opciones_cabecera', 'manager'),
    ('carrito.opciones_cabecera', 'super_admin'),
    ('carrito.opciones_cabecera', 'developer'),
    ('carrito.carga_masiva_oferta_precio_manual', 'sales'),
    ('carrito.carga_masiva_oferta_precio_manual', 'account_manager'),
    ('carrito.carga_masiva_oferta_precio_manual', 'konnen'),
    ('carrito.carga_masiva_oferta_precio_manual', 'manager'),
    ('carrito.carga_masiva_oferta_precio_manual', 'super_admin'),
    ('carrito.carga_masiva_oferta_precio_manual', 'developer'),
    ('carrito.cambiar_centro', 'sales'),
    ('carrito.cambiar_centro', 'account_manager'),
    ('carrito.cambiar_centro', 'konnen'),
    ('carrito.cambiar_centro', 'manager'),
    ('carrito.cambiar_centro', 'super_admin'),
    ('carrito.cambiar_centro', 'developer'),
    ('carrito.anular_con_motivo', 'sales'),
    ('carrito.anular_con_motivo', 'account_manager'),
    ('carrito.anular_con_motivo', 'manager'),
    ('carrito.anular_con_motivo', 'super_admin'),
    ('carrito.anular_con_motivo', 'developer'),
    ('carrito.vendedor_referenciado', 'sales'),
    ('carrito.vendedor_referenciado', 'account_manager'),
    ('carrito.vendedor_referenciado', 'konnen'),
    ('carrito.vendedor_referenciado', 'manager'),
    ('carrito.vendedor_referenciado', 'super_admin'),
    ('carrito.vendedor_referenciado', 'developer'),
    ('carrito.vendedor_referenciado_kiosco', 'client'),
    ('carrito.recuperar_sin_forzar_centro', 'sales'),
    ('carrito.recuperar_sin_forzar_centro', 'account_manager'),
    ('carrito.recuperar_sin_forzar_centro', 'manager'),
    ('carrito.recuperar_sin_forzar_centro', 'super_admin'),
    ('carrito.recuperar_sin_forzar_centro', 'developer'),
    ('cupones.usar', 'sales'),
    ('cupones.usar', 'account_manager'),
    ('cupones.usar', 'finance'),
    ('cupones.usar', 'manager'),
    ('cupones.usar', 'accounts_payable'),
    ('cupones.usar', 'super_admin'),
    ('cupones.usar', 'developer'),
    ('cupones.usar', 'client'),
    ('cupones.usar', 'supplier'),
    ('envio.bonificar', 'sales'),
    ('envio.bonificar', 'account_manager'),
    ('envio.bonificar', 'konnen'),
    ('envio.bonificar', 'manager'),
    ('envio.bonificar', 'super_admin'),
    ('envio.bonificar', 'developer'),
    ('carrito.agregar', 'sales'),
    ('carrito.agregar', 'account_manager'),
    ('carrito.agregar', 'konnen'),
    ('carrito.agregar', 'finance'),
    ('carrito.agregar', 'manager'),
    ('carrito.agregar', 'super_admin'),
    ('carrito.agregar', 'developer'),
    ('carrito.agregar', 'client'),
    ('cotizacion.guardar_en_cualquier_paso', 'sales'),
    ('cotizacion.guardar_en_cualquier_paso', 'account_manager'),
    ('cotizacion.guardar_en_cualquier_paso', 'manager'),
    ('cotizacion.guardar_en_cualquier_paso', 'super_admin'),
    ('cotizacion.guardar_en_cualquier_paso', 'developer'),
    ('cotizacion.crear', 'sales'),
    ('cotizacion.crear', 'account_manager'),
    ('cotizacion.crear', 'konnen'),
    ('cotizacion.crear', 'finance'),
    ('cotizacion.crear', 'manager'),
    ('cotizacion.crear', 'super_admin'),
    ('cotizacion.crear', 'developer'),
    ('cotizacion.crear', 'client'),
    ('cotizacion.crear_especial', 'sales'),
    ('cotizacion.crear_especial', 'account_manager'),
    ('cotizacion.crear_especial', 'manager'),
    ('cotizacion.crear_especial', 'super_admin'),
    ('cotizacion.crear_especial', 'developer'),
    ('pedido.emitir', 'sales'),
    ('pedido.emitir', 'konnen'),
    ('pedido.emitir', 'finance'),
    ('pedido.emitir', 'manager'),
    ('pedido.emitir', 'accounts_payable'),
    ('pedido.emitir', 'super_admin'),
    ('pedido.emitir', 'developer'),
    ('pedido.emitir', 'client'),
    ('pedido.emitir', 'supplier'),
    ('pedido.exigir_mail_confirmacion', 'sales'),
    ('pedido.exigir_mail_confirmacion', 'account_manager'),
    ('pedido.exigir_mail_confirmacion', 'konnen'),
    ('pedido.exigir_mail_confirmacion', 'manager'),
    ('pedido.exigir_mail_confirmacion', 'super_admin'),
    ('pedido.exigir_mail_confirmacion', 'developer'),
    ('pedido.finalidad', 'sales'),
    ('pedido.finalidad', 'account_manager'),
    ('pedido.finalidad', 'konnen'),
    ('pedido.finalidad', 'manager'),
    ('pedido.finalidad', 'super_admin'),
    ('pedido.finalidad', 'developer'),
    ('pedido.consignacion', 'sales'),
    ('pedido.consignacion', 'account_manager'),
    ('pedido.consignacion', 'manager'),
    ('pedido.consignacion', 'super_admin'),
    ('pedido.consignacion', 'developer'),
    ('pedido.pago_mostrador', 'client'),
    ('pedido.ofrecer_retiro_mostrador', 'sales'),
    ('pedido.ofrecer_retiro_mostrador', 'account_manager'),
    ('pedido.ofrecer_retiro_mostrador', 'manager'),
    ('pedido.ofrecer_retiro_mostrador', 'super_admin'),
    ('pedido.ofrecer_retiro_mostrador', 'developer'),
    ('pago.condiciones_adicionales', 'sales'),
    ('pago.condiciones_adicionales', 'account_manager'),
    ('pago.condiciones_adicionales', 'manager'),
    ('pago.condiciones_adicionales', 'super_admin'),
    ('pago.condiciones_adicionales', 'developer'),
    ('pago.cambiar_moneda', 'super_admin'),
    ('pago.cambiar_moneda', 'developer'),
    ('pedido.ver_muestras_gratis', 'sales'),
    ('pedido.ver_muestras_gratis', 'account_manager'),
    ('pedido.ver_muestras_gratis', 'manager'),
    ('pedido.ver_muestras_gratis', 'super_admin'),
    ('pedido.ver_muestras_gratis', 'developer'),
    ('pedido.ver_aviso_pago', 'client'),
    ('documento.elegir_posiciones', 'sales'),
    ('documento.elegir_posiciones', 'account_manager'),
    ('documento.elegir_posiciones', 'konnen'),
    ('documento.elegir_posiciones', 'manager'),
    ('documento.elegir_posiciones', 'super_admin'),
    ('documento.elegir_posiciones', 'developer'),
    ('documento.copiar_cotizacion', 'sales'),
    ('documento.copiar_cotizacion', 'account_manager'),
    ('documento.copiar_cotizacion', 'manager'),
    ('documento.copiar_cotizacion', 'super_admin'),
    ('documento.copiar_cotizacion', 'developer'),
    ('documento.actualizar_oferta_especial', 'sales'),
    ('documento.actualizar_oferta_especial', 'account_manager'),
    ('documento.actualizar_oferta_especial', 'manager'),
    ('documento.actualizar_oferta_especial', 'super_admin'),
    ('documento.actualizar_oferta_especial', 'developer'),
    ('documento.omitir_control_centro', 'sales'),
    ('documento.omitir_control_centro', 'account_manager'),
    ('documento.omitir_control_centro', 'manager'),
    ('documento.omitir_control_centro', 'super_admin'),
    ('documento.omitir_control_centro', 'developer'),
    ('documento.ver_condiciones_internas', 'sales'),
    ('documento.ver_condiciones_internas', 'account_manager'),
    ('documento.ver_condiciones_internas', 'konnen'),
    ('documento.ver_condiciones_internas', 'manager'),
    ('documento.ver_condiciones_internas', 'super_admin'),
    ('documento.ver_condiciones_internas', 'developer'),
    ('mi_cuenta.compras', 'sales'),
    ('mi_cuenta.compras', 'account_manager'),
    ('mi_cuenta.compras', 'konnen'),
    ('mi_cuenta.compras', 'finance'),
    ('mi_cuenta.compras', 'manager'),
    ('mi_cuenta.compras', 'accounts_payable'),
    ('mi_cuenta.compras', 'super_admin'),
    ('mi_cuenta.compras', 'developer'),
    ('mi_cuenta.compras', 'client'),
    ('mi_cuenta.compras', 'supplier'),
    ('mi_cuenta.ventas', 'accounts_payable'),
    ('mi_cuenta.ventas', 'supplier'),
    ('mi_cuenta.ayuda', 'sales'),
    ('mi_cuenta.ayuda', 'account_manager'),
    ('mi_cuenta.ayuda', 'konnen'),
    ('mi_cuenta.ayuda', 'finance'),
    ('mi_cuenta.ayuda', 'manager'),
    ('mi_cuenta.ayuda', 'accounts_payable'),
    ('mi_cuenta.ayuda', 'super_admin'),
    ('mi_cuenta.ayuda', 'developer'),
    ('mi_cuenta.ayuda', 'client'),
    ('mi_cuenta.ayuda', 'supplier'),
    ('mi_cuenta.centro_ayuda', 'sales'),
    ('mi_cuenta.centro_ayuda', 'account_manager'),
    ('mi_cuenta.centro_ayuda', 'finance'),
    ('mi_cuenta.centro_ayuda', 'manager'),
    ('mi_cuenta.centro_ayuda', 'accounts_payable'),
    ('mi_cuenta.centro_ayuda', 'super_admin'),
    ('mi_cuenta.centro_ayuda', 'developer'),
    ('mi_cuenta.centro_ayuda', 'client'),
    ('mi_cuenta.centro_ayuda', 'supplier'),
    ('mi_cuenta.estado_cuenta', 'sales'),
    ('mi_cuenta.estado_cuenta', 'account_manager'),
    ('mi_cuenta.estado_cuenta', 'finance'),
    ('mi_cuenta.estado_cuenta', 'manager'),
    ('mi_cuenta.estado_cuenta', 'accounts_payable'),
    ('mi_cuenta.estado_cuenta', 'super_admin'),
    ('mi_cuenta.estado_cuenta', 'developer'),
    ('mi_cuenta.estado_cuenta', 'client'),
    ('mi_cuenta.estado_cuenta', 'supplier'),
    ('mi_cuenta.legajo_impositivo', 'sales'),
    ('mi_cuenta.legajo_impositivo', 'account_manager'),
    ('mi_cuenta.legajo_impositivo', 'konnen'),
    ('mi_cuenta.legajo_impositivo', 'finance'),
    ('mi_cuenta.legajo_impositivo', 'manager'),
    ('mi_cuenta.legajo_impositivo', 'accounts_payable'),
    ('mi_cuenta.legajo_impositivo', 'super_admin'),
    ('mi_cuenta.legajo_impositivo', 'developer'),
    ('mi_cuenta.legajo_impositivo', 'client'),
    ('mi_cuenta.legajo_impositivo', 'supplier'),
    ('mi_cuenta.mis_codigos', 'sales'),
    ('mi_cuenta.mis_codigos', 'account_manager'),
    ('mi_cuenta.mis_codigos', 'konnen'),
    ('mi_cuenta.mis_codigos', 'finance'),
    ('mi_cuenta.mis_codigos', 'manager'),
    ('mi_cuenta.mis_codigos', 'accounts_payable'),
    ('mi_cuenta.mis_codigos', 'super_admin'),
    ('mi_cuenta.mis_codigos', 'developer'),
    ('mi_cuenta.mis_codigos', 'client'),
    ('mi_cuenta.mis_codigos', 'supplier'),
    ('mi_cuenta.direcciones', 'sales'),
    ('mi_cuenta.direcciones', 'account_manager'),
    ('mi_cuenta.direcciones', 'konnen'),
    ('mi_cuenta.direcciones', 'finance'),
    ('mi_cuenta.direcciones', 'manager'),
    ('mi_cuenta.direcciones', 'accounts_payable'),
    ('mi_cuenta.direcciones', 'super_admin'),
    ('mi_cuenta.direcciones', 'developer'),
    ('mi_cuenta.direcciones', 'client'),
    ('mi_cuenta.cambiar_contrasena', 'client'),
    ('mi_cuenta.cambiar_contrasena', 'supplier'),
    ('personas.gestionar', 'sales'),
    ('personas.gestionar', 'account_manager'),
    ('personas.gestionar', 'konnen'),
    ('personas.gestionar', 'finance'),
    ('personas.gestionar', 'manager'),
    ('personas.gestionar', 'super_admin'),
    ('personas.gestionar', 'developer'),
    ('personas.gestionar', 'client'),
    ('personas.gestionar', 'supplier'),
    ('personas.favoritas', 'sales'),
    ('personas.favoritas', 'account_manager'),
    ('personas.favoritas', 'konnen'),
    ('personas.favoritas', 'manager'),
    ('personas.favoritas', 'super_admin'),
    ('personas.favoritas', 'developer'),
    ('comprobantes_pago.ver', 'sales'),
    ('comprobantes_pago.ver', 'account_manager'),
    ('comprobantes_pago.ver', 'konnen'),
    ('comprobantes_pago.ver', 'finance'),
    ('comprobantes_pago.ver', 'manager'),
    ('comprobantes_pago.ver', 'super_admin'),
    ('comprobantes_pago.ver', 'developer'),
    ('comprobantes_pago.ver', 'client'),
    ('reclamos.modo_asesor', 'sales'),
    ('reclamos.modo_asesor', 'account_manager'),
    ('reclamos.modo_asesor', 'manager'),
    ('reclamos.modo_asesor', 'super_admin'),
    ('reclamos.modo_asesor', 'developer'),
    ('reclamos.notas_internas', 'sales'),
    ('reclamos.notas_internas', 'account_manager'),
    ('reclamos.notas_internas', 'konnen'),
    ('reclamos.notas_internas', 'manager'),
    ('reclamos.notas_internas', 'super_admin'),
    ('reclamos.notas_internas', 'developer'),
    ('crm.gestionar_contactos', 'sales'),
    ('crm.gestionar_contactos', 'account_manager'),
    ('crm.gestionar_contactos', 'manager'),
    ('crm.gestionar_contactos', 'super_admin'),
    ('crm.gestionar_contactos', 'developer'),
    ('konnen.busqueda', 'konnen'),
    ('konnen.documentos', 'konnen'),
    ('cuenta_cliente.usar', 'client'),
    ('cuenta_proveedor.usar', 'supplier'),
    ('proveedores.portal', 'accounts_payable'),
    ('proveedores.portal', 'super_admin'),
    ('proveedores.portal', 'developer'),
    ('proveedores.portal', 'supplier'),
    ('proveedor.operar_como', 'accounts_payable'),
    ('pedidos_bloqueados.filtrar_por_asesor', 'account_manager'),
    ('transportes.ver_horarios', 'sales'),
    ('transportes.ver_horarios', 'account_manager'),
    ('transportes.ver_horarios', 'konnen'),
    ('transportes.ver_horarios', 'manager'),
    ('transportes.ver_horarios', 'super_admin'),
    ('transportes.ver_horarios', 'developer'),
    ('transportes.crear', 'sales'),
    ('transportes.crear', 'account_manager'),
    ('transportes.crear', 'manager'),
    ('transportes.crear', 'super_admin'),
    ('transportes.crear', 'developer'),
    ('sistema.log_sap', 'super_admin'),
    ('sistema.log_sap', 'developer'),
    ('sistema.debug_carrito', 'super_admin'),
    ('sistema.debug_carrito', 'developer'),
    ('sistema.marcas_desarrollo', 'super_admin'),
    ('sistema.marcas_desarrollo', 'developer'),
    ('sistema.no_informar_usuario_sap', 'super_admin'),
    ('sistema.no_informar_usuario_sap', 'developer'),
    ('totem.generar_ticket', 'super_admin'),
    ('totem.generar_ticket', 'developer'),
    ('totem.ver_tickets_en_espera', 'super_admin'),
    ('totem.ver_tickets_en_espera', 'developer'),
    ('producto.mantenimiento', 'super_admin'),
    ('producto.mantenimiento', 'developer'),
    ('gestion.ingresar', 'gestion_planning'),
    ('gestion.ingresar', 'gestion_content'),
    ('gestion.ingresar', 'gestion_accounts_payable'),
    ('gestion.ingresar', 'gestion_accounting_tax'),
    ('gestion.ingresar', 'gestion_admin'),
    ('roles.administrar', 'gestion_admin'),
    ('usuarios.administrar_internos', 'gestion_admin'),
    ('user.index', 'gestion_accounts_payable'),
    ('user.index', 'gestion_admin'),
    ('user.create', 'gestion_accounts_payable'),
    ('user.create', 'gestion_admin'),
    ('user.edit', 'gestion_accounts_payable'),
    ('user.edit', 'gestion_admin'),
    ('user.delete', 'gestion_accounts_payable'),
    ('user.delete', 'gestion_admin'),
    ('product.index', 'gestion_planning'),
    ('product.index', 'gestion_admin'),
    ('payment.index', 'gestion_admin'),
    ('client-code.index', 'gestion_planning'),
    ('client-code.index', 'gestion_admin'),
    ('client-code.create', 'gestion_planning'),
    ('client-code.create', 'gestion_admin'),
    ('client-code.destroy', 'gestion_planning'),
    ('client-code.destroy', 'gestion_admin'),
    ('list.index', 'gestion_admin'),
    ('list.show', 'gestion_admin'),
    ('list.create', 'gestion_admin'),
    ('list.destroy', 'gestion_admin'),
    ('legajo.index', 'gestion_accounting_tax'),
    ('legajo.index', 'gestion_admin'),
    ('legajo.update', 'gestion_accounting_tax'),
    ('legajo.update', 'gestion_admin'),
    ('materials.index', 'gestion_admin'),
    ('materials.show', 'gestion_admin'),
    ('materials.create', 'gestion_admin'),
    ('materials.destroy', 'gestion_admin'),
    ('lead.index', 'gestion_planning'),
    ('lead.index', 'gestion_content'),
    ('lead.index', 'gestion_admin'),
    ('tag.index', 'gestion_planning'),
    ('tag.index', 'gestion_content'),
    ('tag.index', 'gestion_admin'),
    ('tag.create', 'gestion_planning'),
    ('tag.create', 'gestion_content'),
    ('tag.create', 'gestion_admin'),
    ('tag.edit', 'gestion_planning'),
    ('tag.edit', 'gestion_content'),
    ('tag.edit', 'gestion_admin'),
    ('tag.destroy', 'gestion_planning'),
    ('tag.destroy', 'gestion_content'),
    ('tag.destroy', 'gestion_admin'),
    ('filter-order.index', 'gestion_planning'),
    ('filter-order.index', 'gestion_content'),
    ('filter-order.index', 'gestion_admin'),
    ('filter-order.show', 'gestion_planning'),
    ('filter-order.show', 'gestion_content'),
    ('filter-order.show', 'gestion_admin'),
    ('filter-order.update', 'gestion_planning'),
    ('filter-order.update', 'gestion_content'),
    ('filter-order.update', 'gestion_admin'),
    ('component-types.types', 'gestion_planning'),
    ('component-types.types', 'gestion_content'),
    ('component-types.types', 'gestion_admin'),
    ('component-types.index', 'gestion_planning'),
    ('component-types.index', 'gestion_content'),
    ('component-types.index', 'gestion_admin'),
    ('components.index', 'gestion_planning'),
    ('components.index', 'gestion_content'),
    ('components.index', 'gestion_admin'),
    ('components.create', 'gestion_planning'),
    ('components.create', 'gestion_content'),
    ('components.create', 'gestion_admin'),
    ('components.component.edit', 'gestion_planning'),
    ('components.component.edit', 'gestion_content'),
    ('components.component.edit', 'gestion_admin'),
    ('components.component.delete', 'gestion_planning'),
    ('components.component.delete', 'gestion_content'),
    ('components.component.delete', 'gestion_admin'),
    ('logos.index', 'gestion_planning'),
    ('logos.index', 'gestion_content'),
    ('logos.index', 'gestion_admin'),
    ('logos.create', 'gestion_planning'),
    ('logos.create', 'gestion_content'),
    ('logos.create', 'gestion_admin'),
    ('logos.logo.edit', 'gestion_planning'),
    ('logos.logo.edit', 'gestion_content'),
    ('logos.logo.edit', 'gestion_admin'),
    ('logos.logo.delete', 'gestion_planning'),
    ('logos.logo.delete', 'gestion_content'),
    ('logos.logo.delete', 'gestion_admin'),
    ('hierarchy-node.index', 'gestion_planning'),
    ('hierarchy-node.index', 'gestion_content'),
    ('hierarchy-node.index', 'gestion_admin'),
    ('hierarchy-node.create', 'gestion_planning'),
    ('hierarchy-node.create', 'gestion_content'),
    ('hierarchy-node.create', 'gestion_admin'),
    ('hierarchy-node.node.edit', 'gestion_planning'),
    ('hierarchy-node.node.edit', 'gestion_content'),
    ('hierarchy-node.node.edit', 'gestion_admin'),
    ('hierarchy-node.node.delete', 'gestion_planning'),
    ('hierarchy-node.node.delete', 'gestion_content'),
    ('hierarchy-node.node.delete', 'gestion_admin'),
    ('team.index', 'gestion_content'),
    ('team.index', 'gestion_admin'),
    ('team.create', 'gestion_content'),
    ('team.create', 'gestion_admin'),
    ('team.edit', 'gestion_content'),
    ('team.edit', 'gestion_admin'),
    ('team.delete', 'gestion_content'),
    ('team.delete', 'gestion_admin'),
    ('messages.index', 'gestion_admin'),
    ('messages.create', 'gestion_admin'),
    ('messages.message.edit', 'gestion_admin'),
    ('messages.message.delete', 'gestion_admin'),
    ('notifications.index', 'gestion_planning'),
    ('notifications.index', 'gestion_content'),
    ('notifications.index', 'gestion_admin'),
    ('notifications.create', 'gestion_planning'),
    ('notifications.create', 'gestion_content'),
    ('notifications.create', 'gestion_admin'),
    ('notifications.notification.edit', 'gestion_planning'),
    ('notifications.notification.edit', 'gestion_content'),
    ('notifications.notification.edit', 'gestion_admin'),
    ('notifications.notification.delete', 'gestion_planning'),
    ('notifications.notification.delete', 'gestion_content'),
    ('notifications.notification.delete', 'gestion_admin'),
    ('feature-flags.index', 'gestion_admin'),
    ('feature-flags.create', 'gestion_admin'),
    ('feature-flags.feature-flag.edit', 'gestion_admin'),
    ('feature-flags.feature-flag.delete', 'gestion_admin'),
    ('certificacion.index', 'gestion_admin'),
    ('certificacion.update', 'gestion_admin'),
    ('calidad.index', 'gestion_admin'),
    ('calidad.update', 'gestion_admin'),
    ('segments.index', 'gestion_planning'),
    ('segments.index', 'gestion_content'),
    ('segments.index', 'gestion_admin'),
    ('segments.create', 'gestion_planning'),
    ('segments.create', 'gestion_content'),
    ('segments.create', 'gestion_admin'),
    ('segments.segment.edit', 'gestion_planning'),
    ('segments.segment.edit', 'gestion_content'),
    ('segments.segment.edit', 'gestion_admin'),
    ('segments.segment.delete', 'gestion_planning'),
    ('segments.segment.delete', 'gestion_content'),
    ('segments.segment.delete', 'gestion_admin'),
    ('empresas.index', 'gestion_admin'),
    ('header-links.index', 'gestion_admin'),
    ('header-links.create', 'gestion_admin'),
    ('header-links.link.edit', 'gestion_admin'),
    ('header-links.link.delete', 'gestion_admin'),
    ('info.library.index', 'gestion_admin'),
    ('info.library.collections.index', 'gestion_admin'),
    ('info.library.collections.create', 'gestion_admin'),
    ('info.library.collections.collection.edit', 'gestion_admin'),
    ('info.library.collections.collection.delete', 'gestion_admin'),
    ('info.library.articles.index', 'gestion_admin'),
    ('info.library.articles.create', 'gestion_admin'),
    ('info.library.articles.article.edit', 'gestion_admin'),
    ('info.library.articles.article.delete', 'gestion_admin'),
    ('info.facts.index', 'gestion_admin'),
    ('info.facts.create', 'gestion_admin'),
    ('info.facts.fact.edit', 'gestion_admin'),
    ('info.facts.fact.delete', 'gestion_admin'),
    ('footer.index', 'gestion_admin'),
    ('footer.edit', 'gestion_admin');

DROP TEMPORARY TABLE IF EXISTS pin_permisos_nuevos;
CREATE TEMPORARY TABLE pin_permisos_nuevos (slug VARCHAR(80) NOT NULL PRIMARY KEY) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO pin_permisos_nuevos (slug)
SELECT c.slug FROM pin_permisos_catalogo c
WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.slug = c.slug);

INSERT INTO roles (slug, name, ` + "`" + `system` + "`" + `, ` + "`" + `order` + "`" + `, legacy_role, active, created_at, updated_at)
SELECT r.slug, r.name, r.` + "`" + `system` + "`" + `, r.` + "`" + `order` + "`" + `, r.legacy_role, 1, NOW(), NOW()
FROM pin_permisos_roles r
WHERE NOT EXISTS (SELECT 1 FROM roles x WHERE x.slug = r.slug);
SET @roles_nuevos = ROW_COUNT();

INSERT INTO permissions (slug, name, type, active, ` + "`" + `order` + "`" + `, created_at, updated_at)
SELECT c.slug, c.name, c.type, 1, c.` + "`" + `order` + "`" + `, NOW(), NOW()
FROM pin_permisos_catalogo c
JOIN pin_permisos_nuevos n ON n.slug = c.slug;
SET @permisos_nuevos = ROW_COUNT();

INSERT IGNORE INTO role_has_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM pin_permisos_iniciales i
JOIN pin_permisos_nuevos n ON n.slug = i.permiso
JOIN permissions p ON p.slug = i.permiso
JOIN roles r ON r.slug = i.rol;
SET @asignaciones = ROW_COUNT();

UPDATE permissions p
JOIN pin_permisos_catalogo c ON c.slug = p.slug
SET p.type = c.type, p.active = 1, p.updated_at = NOW()
WHERE p.type <> c.type OR p.active <> 1;
SET @permisos_actualizados = ROW_COUNT();

UPDATE permissions p
SET p.active = 0, p.updated_at = NOW()
WHERE p.active = 1
  AND NOT EXISTS (SELECT 1 FROM pin_permisos_catalogo c WHERE c.slug = p.slug);
SET @permisos_desactivados = ROW_COUNT();

DROP TEMPORARY TABLE pin_permisos_nuevos;
DROP TEMPORARY TABLE pin_permisos_iniciales;
DROP TEMPORARY TABLE pin_permisos_catalogo;
DROP TEMPORARY TABLE pin_permisos_roles;

COMMIT;

SELECT '1.7.0' AS catalogo, @roles_nuevos AS roles_nuevos, @permisos_nuevos AS permisos_nuevos,
    @asignaciones AS asignaciones, @permisos_actualizados AS permisos_actualizados,
    @permisos_desactivados AS permisos_desactivados;
`

// Sentencias parte un SQL del paquete: cada sentencia termina en ';' al final
// de una línea. Saca los comentarios.
func Sentencias(texto string) []string {
	var sentencias []string
	var actual strings.Builder
	for _, linea := range strings.Split(strings.ReplaceAll(texto, "\r\n", "\n"), "\n") {
		limpia := strings.TrimSpace(linea)
		if limpia == "" || strings.HasPrefix(limpia, "--") {
			continue
		}
		actual.WriteString(linea)
		actual.WriteString("\n")
		if strings.HasSuffix(limpia, ";") {
			sentencias = append(sentencias, strings.TrimSuffix(strings.TrimSpace(actual.String()), ";"))
			actual.Reset()
		}
	}
	if resto := strings.TrimSpace(actual.String()); resto != "" {
		sentencias = append(sentencias, resto)
	}
	return sentencias
}

// Sincronizar crea las tablas que falten y sincroniza roles y permisos con el
// catálogo. Usa una sola conexión: las tablas temporales viven en ella.
func Sincronizar(ctx context.Context, db *sql.DB) error {
	conn, err := db.Conn(ctx)
	if err != nil {
		return err
	}
	defer conn.Close()

	for _, sentencia := range append(Sentencias(SQLEsquema), Sentencias(SQLSincronizar)...) {
		if _, err := conn.ExecContext(ctx, sentencia); err != nil {
			_, _ = conn.ExecContext(ctx, "ROLLBACK")
			return err
		}
	}
	return nil
}
