<?php

declare(strict_types=1);

// Generado por bin/generar.php a partir de catalogo/permisos.json (versión 1.5.0).
// No editar a mano: cambiar el JSON y volver a generar.

namespace Famiq\PinPermisos;

/**
 * Catálogo de permisos de la PIN.
 *
 *     $this->isGranted(Permissions::ClienteOperarComo->attr());
 *     #[IsGranted('PERM_cliente.operar_como')]
 *     {% if is_granted('PERM_cliente.operar_como') %}
 */
enum Permissions: string
{
    /** Prefijo de los atributos de seguridad, para distinguir permisos de roles. */
    public const PREFIJO = 'PERM_';

    case PinIngresar = 'pin.ingresar';
    case MiCuentaIngresar = 'mi_cuenta.ingresar';
    case MisGestionesIngresar = 'mis_gestiones.ingresar';
    case ClienteElegirObligatorio = 'cliente.elegir_obligatorio';
    case ChatAyudaVer = 'chat_ayuda.ver';
    case EncuestaResponder = 'encuesta.responder';
    case ClienteOperarComo = 'cliente.operar_como';
    case CatalogoVerComoVendedor = 'catalogo.ver_como_vendedor';
    case ClienteDarDeAlta = 'cliente.dar_de_alta';
    case ClienteVerInformacionInterna = 'cliente.ver_informacion_interna';
    case ClienteVerNotas = 'cliente.ver_notas';
    case VendedorIdSap = 'vendedor.id_sap';
    case ProductosEspecialesVer = 'productos_especiales.ver';
    case PrecioVerStandard = 'precio.ver_standard';
    case ProductoVerMarcasInternas = 'producto.ver_marcas_internas';
    case ProductoVerDescuentoMaximo = 'producto.ver_descuento_maximo';
    case StockVerPorSucursal = 'stock.ver_por_sucursal';
    case CatalogoVerDatosTecnicos = 'catalogo.ver_datos_tecnicos';
    case RecortesVerDepositoOrigen = 'recortes.ver_deposito_origen';
    case PoliticaPreciosDescargar = 'politica_precios.descargar';
    case ProductoVerPrecioSinDescuento = 'producto.ver_precio_sin_descuento';
    case CatalogoVerComoComprar = 'catalogo.ver_como_comprar';
    case ListasUsar = 'listas.usar';
    case ListasCrearFamiq = 'listas.crear_famiq';
    case ListasEditarFamiq = 'listas.editar_famiq';
    case ListasDescargarReporte = 'listas.descargar_reporte';
    case CarritoPrecioManual = 'carrito.precio_manual';
    case CarritoNotas = 'carrito.notas';
    case CarritoAlternativas = 'carrito.alternativas';
    case CarritoOpcionesCabecera = 'carrito.opciones_cabecera';
    case CarritoCargaMasivaOfertaPrecioManual = 'carrito.carga_masiva_oferta_precio_manual';
    case CarritoCambiarCentro = 'carrito.cambiar_centro';
    case CarritoAnularConMotivo = 'carrito.anular_con_motivo';
    case CarritoVendedorReferenciado = 'carrito.vendedor_referenciado';
    case CarritoVendedorReferenciadoKiosco = 'carrito.vendedor_referenciado_kiosco';
    case CarritoRecuperarSinForzarCentro = 'carrito.recuperar_sin_forzar_centro';
    case CuponesUsar = 'cupones.usar';
    case EnvioBonificar = 'envio.bonificar';
    case CarritoAgregar = 'carrito.agregar';
    case CotizacionGuardarEnCualquierPaso = 'cotizacion.guardar_en_cualquier_paso';
    case CotizacionCrear = 'cotizacion.crear';
    case CotizacionCrearEspecial = 'cotizacion.crear_especial';
    case PedidoEmitir = 'pedido.emitir';
    case PedidoExigirMailConfirmacion = 'pedido.exigir_mail_confirmacion';
    case PedidoFinalidad = 'pedido.finalidad';
    case PedidoConsignacion = 'pedido.consignacion';
    case PedidoPagoMostrador = 'pedido.pago_mostrador';
    case PedidoOfrecerRetiroMostrador = 'pedido.ofrecer_retiro_mostrador';
    case PagoCondicionesAdicionales = 'pago.condiciones_adicionales';
    case PagoCambiarMoneda = 'pago.cambiar_moneda';
    case PedidoVerMuestrasGratis = 'pedido.ver_muestras_gratis';
    case PedidoVerAvisoPago = 'pedido.ver_aviso_pago';
    case DocumentoElegirPosiciones = 'documento.elegir_posiciones';
    case DocumentoCopiarCotizacion = 'documento.copiar_cotizacion';
    case DocumentoActualizarOfertaEspecial = 'documento.actualizar_oferta_especial';
    case DocumentoOmitirControlCentro = 'documento.omitir_control_centro';
    case DocumentoVerCondicionesInternas = 'documento.ver_condiciones_internas';
    case MiCuentaCompras = 'mi_cuenta.compras';
    case MiCuentaVentas = 'mi_cuenta.ventas';
    case MiCuentaAyuda = 'mi_cuenta.ayuda';
    case MiCuentaCentroAyuda = 'mi_cuenta.centro_ayuda';
    case MiCuentaEstadoCuenta = 'mi_cuenta.estado_cuenta';
    case MiCuentaLegajoImpositivo = 'mi_cuenta.legajo_impositivo';
    case MiCuentaMisCodigos = 'mi_cuenta.mis_codigos';
    case MiCuentaDirecciones = 'mi_cuenta.direcciones';
    case MiCuentaCambiarContrasena = 'mi_cuenta.cambiar_contrasena';
    case PersonasGestionar = 'personas.gestionar';
    case PersonasFavoritas = 'personas.favoritas';
    case ComprobantesPagoVer = 'comprobantes_pago.ver';
    case ReclamosModoAsesor = 'reclamos.modo_asesor';
    case ReclamosNotasInternas = 'reclamos.notas_internas';
    case CrmGestionarContactos = 'crm.gestionar_contactos';
    case KonnenBusqueda = 'konnen.busqueda';
    case KonnenDocumentos = 'konnen.documentos';
    case CuentaClienteUsar = 'cuenta_cliente.usar';
    case CuentaProveedorUsar = 'cuenta_proveedor.usar';
    case ProveedoresPortal = 'proveedores.portal';
    case ProveedorOperarComo = 'proveedor.operar_como';
    case PedidosBloqueadosFiltrarPorAsesor = 'pedidos_bloqueados.filtrar_por_asesor';
    case TransportesVerHorarios = 'transportes.ver_horarios';
    case TransportesCrear = 'transportes.crear';
    case SistemaLogSap = 'sistema.log_sap';
    case SistemaDebugCarrito = 'sistema.debug_carrito';
    case SistemaMarcasDesarrollo = 'sistema.marcas_desarrollo';
    case SistemaNoInformarUsuarioSap = 'sistema.no_informar_usuario_sap';
    case TotemGenerarTicket = 'totem.generar_ticket';
    case TotemVerTicketsEnEspera = 'totem.ver_tickets_en_espera';
    case ProductoMantenimiento = 'producto.mantenimiento';
    case GestionIngresar = 'gestion.ingresar';
    case RolesAdministrar = 'roles.administrar';
    case UsuariosAdministrarInternos = 'usuarios.administrar_internos';
    case UserIndex = 'user.index';
    case UserCreate = 'user.create';
    case UserEdit = 'user.edit';
    case UserDelete = 'user.delete';
    case ProductIndex = 'product.index';
    case PaymentIndex = 'payment.index';
    case ClientCodeIndex = 'client-code.index';
    case ClientCodeCreate = 'client-code.create';
    case ClientCodeDestroy = 'client-code.destroy';
    case ListIndex = 'list.index';
    case ListShow = 'list.show';
    case ListCreate = 'list.create';
    case ListDestroy = 'list.destroy';
    case LegajoIndex = 'legajo.index';
    case LegajoUpdate = 'legajo.update';
    case MaterialsIndex = 'materials.index';
    case MaterialsShow = 'materials.show';
    case MaterialsCreate = 'materials.create';
    case MaterialsDestroy = 'materials.destroy';
    case LeadIndex = 'lead.index';
    case TagIndex = 'tag.index';
    case TagCreate = 'tag.create';
    case TagEdit = 'tag.edit';
    case TagDestroy = 'tag.destroy';
    case FilterOrderIndex = 'filter-order.index';
    case FilterOrderShow = 'filter-order.show';
    case FilterOrderUpdate = 'filter-order.update';
    case ComponentTypesTypes = 'component-types.types';
    case ComponentTypesIndex = 'component-types.index';
    case ComponentsIndex = 'components.index';
    case ComponentsCreate = 'components.create';
    case ComponentsComponentEdit = 'components.component.edit';
    case ComponentsComponentDelete = 'components.component.delete';
    case LogosIndex = 'logos.index';
    case LogosCreate = 'logos.create';
    case LogosLogoEdit = 'logos.logo.edit';
    case LogosLogoDelete = 'logos.logo.delete';
    case HierarchyNodeIndex = 'hierarchy-node.index';
    case HierarchyNodeCreate = 'hierarchy-node.create';
    case HierarchyNodeNodeEdit = 'hierarchy-node.node.edit';
    case HierarchyNodeNodeDelete = 'hierarchy-node.node.delete';
    case TeamIndex = 'team.index';
    case TeamCreate = 'team.create';
    case TeamEdit = 'team.edit';
    case TeamDelete = 'team.delete';
    case MessagesIndex = 'messages.index';
    case MessagesCreate = 'messages.create';
    case MessagesMessageEdit = 'messages.message.edit';
    case MessagesMessageDelete = 'messages.message.delete';
    case NotificationsIndex = 'notifications.index';
    case NotificationsCreate = 'notifications.create';
    case NotificationsNotificationEdit = 'notifications.notification.edit';
    case NotificationsNotificationDelete = 'notifications.notification.delete';
    case FeatureFlagsIndex = 'feature-flags.index';
    case FeatureFlagsCreate = 'feature-flags.create';
    case FeatureFlagsFeatureFlagEdit = 'feature-flags.feature-flag.edit';
    case FeatureFlagsFeatureFlagDelete = 'feature-flags.feature-flag.delete';
    case CertificacionIndex = 'certificacion.index';
    case CertificacionUpdate = 'certificacion.update';
    case CalidadIndex = 'calidad.index';
    case CalidadUpdate = 'calidad.update';
    case SegmentsIndex = 'segments.index';
    case SegmentsCreate = 'segments.create';
    case SegmentsSegmentEdit = 'segments.segment.edit';
    case SegmentsSegmentDelete = 'segments.segment.delete';
    case EmpresasIndex = 'empresas.index';
    case HeaderLinksIndex = 'header-links.index';
    case HeaderLinksCreate = 'header-links.create';
    case HeaderLinksLinkEdit = 'header-links.link.edit';
    case HeaderLinksLinkDelete = 'header-links.link.delete';
    case InfoLibraryIndex = 'info.library.index';
    case InfoLibraryCollectionsIndex = 'info.library.collections.index';
    case InfoLibraryCollectionsCreate = 'info.library.collections.create';
    case InfoLibraryCollectionsCollectionEdit = 'info.library.collections.collection.edit';
    case InfoLibraryCollectionsCollectionDelete = 'info.library.collections.collection.delete';
    case InfoLibraryArticlesIndex = 'info.library.articles.index';
    case InfoLibraryArticlesCreate = 'info.library.articles.create';
    case InfoLibraryArticlesArticleEdit = 'info.library.articles.article.edit';
    case InfoLibraryArticlesArticleDelete = 'info.library.articles.article.delete';
    case InfoFactsIndex = 'info.facts.index';
    case InfoFactsCreate = 'info.facts.create';
    case InfoFactsFactEdit = 'info.facts.fact.edit';
    case InfoFactsFactDelete = 'info.facts.fact.delete';
    case FooterIndex = 'footer.index';
    case FooterEdit = 'footer.edit';

    /** El atributo tal como se pregunta en isGranted(), IsGranted y is_granted(). */
    public function attr(): string
    {
        return self::PREFIJO . $this->value;
    }

    public static function tryFromAttr(string $atributo): ?self
    {
        if (!str_starts_with($atributo, self::PREFIJO)) {
            return null;
        }

        return self::tryFrom(substr($atributo, strlen(self::PREFIJO)));
    }

    /** Nombre visible en el ABM. */
    public function nombre(): string
    {
        return match ($this) {
            self::PinIngresar => 'Ingresar a la PIN',
            self::MiCuentaIngresar => 'Mi cuenta',
            self::MisGestionesIngresar => 'Mis gestiones',
            self::ClienteElegirObligatorio => 'Elegir cliente antes de operar',
            self::ChatAyudaVer => 'Ver botones de chat',
            self::EncuestaResponder => 'Encuesta de satisfacción',
            self::ClienteOperarComo => 'Operar en nombre de un cliente',
            self::CatalogoVerComoVendedor => 'Catálogo con condiciones de vendedor',
            self::ClienteDarDeAlta => 'Dar de alta clientes',
            self::ClienteVerInformacionInterna => 'Ver información interna del cliente',
            self::ClienteVerNotas => 'Ver notas del cliente',
            self::VendedorIdSap => 'Vendedor Famiq con ID SAP',
            self::ProductosEspecialesVer => 'Ver Productos Especiales',
            self::PrecioVerStandard => 'Ver precio standard',
            self::ProductoVerMarcasInternas => 'Ver marcas internas del producto',
            self::ProductoVerDescuentoMaximo => 'Ver descuento máximo y contrato marco',
            self::StockVerPorSucursal => 'Ver stock por sucursal',
            self::CatalogoVerDatosTecnicos => 'Ver datos técnicos internos',
            self::RecortesVerDepositoOrigen => 'Ver depósito de origen en recortes',
            self::PoliticaPreciosDescargar => 'Descargar política de precios',
            self::ProductoVerPrecioSinDescuento => 'Ver precio sin descuento por presentación',
            self::CatalogoVerComoComprar => 'Ver cómo comprar',
            self::ListasUsar => 'Usar listas y favoritos',
            self::ListasCrearFamiq => 'Crear listas Famiq',
            self::ListasEditarFamiq => 'Editar listas Famiq',
            self::ListasDescargarReporte => 'Descargar reporte de listas',
            self::CarritoPrecioManual => 'Precio manual y moneda',
            self::CarritoNotas => 'Notas en el carrito',
            self::CarritoAlternativas => 'Alternativas de producto',
            self::CarritoOpcionesCabecera => 'Opciones del carrito',
            self::CarritoCargaMasivaOfertaPrecioManual => 'Carga masiva en ofertas de precio manual',
            self::CarritoCambiarCentro => 'Cambiar el centro de las posiciones',
            self::CarritoAnularConMotivo => 'Anular posición con motivo',
            self::CarritoVendedorReferenciado => 'Vendedor referenciado',
            self::CarritoVendedorReferenciadoKiosco => 'Vendedor referenciado desde kiosco',
            self::CarritoRecuperarSinForzarCentro => 'Recuperar carrito sin forzar centro',
            self::CuponesUsar => 'Cupones',
            self::EnvioBonificar => 'Bonificar envío y embalaje',
            self::CarritoAgregar => 'Agregar productos al carrito',
            self::CotizacionGuardarEnCualquierPaso => 'Guardar cotización en cualquier paso',
            self::CotizacionCrear => 'Crear ofertas comunes',
            self::CotizacionCrearEspecial => 'Crear ofertas especiales',
            self::PedidoEmitir => 'Emitir pedidos',
            self::PedidoExigirMailConfirmacion => 'Exigir mail de confirmación',
            self::PedidoFinalidad => 'Finalidad del pedido',
            self::PedidoConsignacion => 'Consignación',
            self::PedidoPagoMostrador => 'Pago en mostrador',
            self::PedidoOfrecerRetiroMostrador => 'Ofrecer retiro en mostrador',
            self::PagoCondicionesAdicionales => 'Condiciones de pago adicionales',
            self::PagoCambiarMoneda => 'Cambiar moneda de pago',
            self::PedidoVerMuestrasGratis => 'Ver pedidos de muestra gratis',
            self::PedidoVerAvisoPago => 'Ver avisos de pago al cliente',
            self::DocumentoElegirPosiciones => 'Elegir posiciones de una cotización',
            self::DocumentoCopiarCotizacion => 'Copiar cotización',
            self::DocumentoActualizarOfertaEspecial => 'Actualizar oferta especial vencida',
            self::DocumentoOmitirControlCentro => 'Abrir documentos de otro centro',
            self::DocumentoVerCondicionesInternas => 'Ver condiciones internas',
            self::MiCuentaCompras => 'Compras y transacciones',
            self::MiCuentaVentas => 'Ventas',
            self::MiCuentaAyuda => 'Ayuda',
            self::MiCuentaCentroAyuda => 'Centro de ayuda',
            self::MiCuentaEstadoCuenta => 'Estado de cuenta',
            self::MiCuentaLegajoImpositivo => 'Legajo impositivo',
            self::MiCuentaMisCodigos => 'Mis códigos',
            self::MiCuentaDirecciones => 'Mis direcciones',
            self::MiCuentaCambiarContrasena => 'Cambiar contraseña',
            self::PersonasGestionar => 'Mis personas',
            self::PersonasFavoritas => 'Personas favoritas',
            self::ComprobantesPagoVer => 'Comprobantes de pago',
            self::ReclamosModoAsesor => 'Reclamos en modo asesor',
            self::ReclamosNotasInternas => 'Notas internas en reclamos',
            self::CrmGestionarContactos => 'Gestionar contactos del CRM',
            self::KonnenBusqueda => 'Búsqueda Konnen',
            self::KonnenDocumentos => 'Documentos Konnen',
            self::CuentaClienteUsar => 'Cuenta cliente',
            self::CuentaProveedorUsar => 'Cuenta proveedor',
            self::ProveedoresPortal => 'Portal de proveedores',
            self::ProveedorOperarComo => 'Operar en nombre de un proveedor',
            self::PedidosBloqueadosFiltrarPorAsesor => 'Filtrar pedidos bloqueados por asesor',
            self::TransportesVerHorarios => 'Ver horarios de transportes',
            self::TransportesCrear => 'Crear transportes',
            self::SistemaLogSap => 'Registro técnico de SAP',
            self::SistemaDebugCarrito => 'Debug del carrito',
            self::SistemaMarcasDesarrollo => 'Marcas de desarrollo en pantalla',
            self::SistemaNoInformarUsuarioSap => 'No informar el usuario a SAP',
            self::TotemGenerarTicket => 'Generar ticket del tótem',
            self::TotemVerTicketsEnEspera => 'Ver tickets en espera del tótem',
            self::ProductoMantenimiento => 'Mantenimiento de productos',
            self::GestionIngresar => 'Ingresar a gestión',
            self::RolesAdministrar => 'Administrar roles y permisos',
            self::UsuariosAdministrarInternos => 'Administrar usuarios internos',
            self::UserIndex => 'Ver usuarios',
            self::UserCreate => 'Crear usuario',
            self::UserEdit => 'Editar usuario',
            self::UserDelete => 'Eliminar usuario',
            self::ProductIndex => 'Ver Productos',
            self::PaymentIndex => 'Ver Pagos',
            self::ClientCodeIndex => 'Ver Código Cliente',
            self::ClientCodeCreate => 'Crear Código Cliente',
            self::ClientCodeDestroy => 'Eliminar Código Cliente',
            self::ListIndex => 'Ver Mis Listas',
            self::ListShow => 'Listas de Empresa',
            self::ListCreate => 'Crear Mis Listas',
            self::ListDestroy => 'Eliminar Lista',
            self::LegajoIndex => 'Ver Legajo impositivo',
            self::LegajoUpdate => 'Editar Legajo impositivo',
            self::MaterialsIndex => 'Ver Materiales con Defectos',
            self::MaterialsShow => 'Ver Material con Defecto',
            self::MaterialsCreate => 'Crear Material con Defecto',
            self::MaterialsDestroy => 'Eliminar Material con Defecto',
            self::LeadIndex => 'Ver Leads',
            self::TagIndex => 'Ver Etiquetas',
            self::TagCreate => 'Crear Etiquetas',
            self::TagEdit => 'Editar Etiqueta',
            self::TagDestroy => 'Eliminar Etiqueta',
            self::FilterOrderIndex => 'Ver Filtros',
            self::FilterOrderShow => 'Ver Ordenamiento de filtros',
            self::FilterOrderUpdate => 'Editar Ordenamiento de filtros',
            self::ComponentTypesTypes => 'Ver Tipos de componentes',
            self::ComponentTypesIndex => 'Ver Componentes de la Sección',
            self::ComponentsIndex => 'Ver Componentes',
            self::ComponentsCreate => 'Crear Componente',
            self::ComponentsComponentEdit => 'Editar Componente',
            self::ComponentsComponentDelete => 'Eliminar Componente',
            self::LogosIndex => 'Ver Logos',
            self::LogosCreate => 'Crear Logo',
            self::LogosLogoEdit => 'Editar Logo',
            self::LogosLogoDelete => 'Eliminar Logo',
            self::HierarchyNodeIndex => 'Ver Nodos',
            self::HierarchyNodeCreate => 'Crear Nodo',
            self::HierarchyNodeNodeEdit => 'Editar Nodo',
            self::HierarchyNodeNodeDelete => 'Eliminar Nodo',
            self::TeamIndex => 'Ver Personal',
            self::TeamCreate => 'Crear Personal',
            self::TeamEdit => 'Editar Personal',
            self::TeamDelete => 'Eliminar Personal',
            self::MessagesIndex => 'Ver Mensajes',
            self::MessagesCreate => 'Crear Mensajes',
            self::MessagesMessageEdit => 'Editar Mensajes',
            self::MessagesMessageDelete => 'Eliminar Mensajes',
            self::NotificationsIndex => 'Ver Novedad',
            self::NotificationsCreate => 'Crear Novedad',
            self::NotificationsNotificationEdit => 'Editar Novedad',
            self::NotificationsNotificationDelete => 'Eliminar Novedad',
            self::FeatureFlagsIndex => 'Ver Funcionalidades',
            self::FeatureFlagsCreate => 'Crear funcionalidad',
            self::FeatureFlagsFeatureFlagEdit => 'Editar Funcionalidades',
            self::FeatureFlagsFeatureFlagDelete => 'Eliminar Funcionalidades',
            self::CertificacionIndex => 'Ver Certificación',
            self::CertificacionUpdate => 'Editar Certificación',
            self::CalidadIndex => 'Ver Política de calidad',
            self::CalidadUpdate => 'Editar Política de calidad',
            self::SegmentsIndex => 'Ver Segmentos',
            self::SegmentsCreate => 'Crear Segmento',
            self::SegmentsSegmentEdit => 'Editar Segmento',
            self::SegmentsSegmentDelete => 'Eliminar Segmento',
            self::EmpresasIndex => 'Ver Empresas',
            self::HeaderLinksIndex => 'Ver Links del header',
            self::HeaderLinksCreate => 'Crear Links del header',
            self::HeaderLinksLinkEdit => 'Editar Links del header',
            self::HeaderLinksLinkDelete => 'Eliminar Links del header',
            self::InfoLibraryIndex => 'Ver Biblioteca',
            self::InfoLibraryCollectionsIndex => 'Ver Colecciones',
            self::InfoLibraryCollectionsCreate => 'Crear Colección',
            self::InfoLibraryCollectionsCollectionEdit => 'Editar Colección',
            self::InfoLibraryCollectionsCollectionDelete => 'Eliminar Colección',
            self::InfoLibraryArticlesIndex => 'Ver Artículos',
            self::InfoLibraryArticlesCreate => 'Crear Artículo',
            self::InfoLibraryArticlesArticleEdit => 'Editar Artículo',
            self::InfoLibraryArticlesArticleDelete => 'Eliminar Artículo',
            self::InfoFactsIndex => 'Ver ¿Sabías qué?',
            self::InfoFactsCreate => 'Crear dato',
            self::InfoFactsFactEdit => 'Editar dato',
            self::InfoFactsFactDelete => 'Eliminar dato',
            self::FooterIndex => 'Ver Footer',
            self::FooterEdit => 'Editar Footer',
        };
    }

    public function descripcion(): string
    {
        return match ($this) {
            self::PinIngresar => 'Entrar al sitio y usar la PIN.',
            self::MiCuentaIngresar => 'Entrar a Mi cuenta.',
            self::MisGestionesIngresar => 'El panel del asesor: elegir cliente, seguimiento, reportes.',
            self::ClienteElegirObligatorio => 'Sin cliente elegido, solo puede usar Mis gestiones y el alta de clientes.',
            self::ChatAyudaVer => 'WhatsApp y chat de ayuda. Sin sesión se siguen viendo.',
            self::EncuestaResponder => 'Recibir la encuesta de satisfacción.',
            self::ClienteOperarComo => 'Elegir un cliente y trabajar por él; mensajes y textos de asesor.',
            self::CatalogoVerComoVendedor => 'Búsqueda y precios del catálogo en modo vendedor; opciones completas de vinilo.',
            self::ClienteDarDeAlta => 'Registrar clientes nuevos a su nombre y volver a Mis gestiones.',
            self::ClienteVerInformacionInterna => 'Clasificación, T1, pagos, bloqueos y score del cliente.',
            self::ClienteVerNotas => 'Notas del cliente en Mi cuenta y en el encabezado.',
            self::VendedorIdSap => 'Valida el ID de SAP del vendedor y habilita la API externa.',
            self::ProductosEspecialesVer => 'La sección Productos Especiales.',
            self::PrecioVerStandard => 'El precio standard en Productos Especiales.',
            self::ProductoVerMarcasInternas => 'Inmovilizado, recortes, cajón cerrado; botón Reportar un problema.',
            self::ProductoVerDescuentoMaximo => 'El tag de descuento máximo y el contrato marco.',
            self::StockVerPorSucursal => 'Stock por sucursal en catálogo, ficha técnica y listas.',
            self::CatalogoVerDatosTecnicos => 'El ID de material y datos técnicos sobre la imagen.',
            self::RecortesVerDepositoOrigen => 'La columna Depósito de Origen en recortes de tubo.',
            self::PoliticaPreciosDescargar => 'El Excel de política de precios.',
            self::ProductoVerPrecioSinDescuento => 'El precio sin descuento según la presentación del producto.',
            self::CatalogoVerComoComprar => 'El bloque "cómo comprar" del pie de página.',
            self::ListasUsar => 'Marcar favoritos y usar listas.',
            self::ListasCrearFamiq => 'Las listas que crea son de Famiq y no personales.',
            self::ListasEditarFamiq => 'Hoy lo decide un mail hardcodeado; pasa a permiso directo de esas personas.',
            self::ListasDescargarReporte => 'El Excel de listas de deseos.',
            self::CarritoPrecioManual => 'Cargar precio manual y elegir moneda por posición.',
            self::CarritoNotas => 'Notas por posición y de cabecera.',
            self::CarritoAlternativas => 'Generar y ordenar alternativas.',
            self::CarritoOpcionesCabecera => 'Agregar alternativas y complementarios automáticos.',
            self::CarritoCargaMasivaOfertaPrecioManual => 'Carga masiva aunque el carrito venga de una oferta con precio manual.',
            self::CarritoCambiarCentro => 'Mover posiciones entre centros y sucursales.',
            self::CarritoAnularConMotivo => 'Pedir el motivo al anular una posición.',
            self::CarritoVendedorReferenciado => 'Gestión referenciada y elegir el vendedor referenciado.',
            self::CarritoVendedorReferenciadoKiosco => 'El cliente en un kiosco elige el vendedor que lo atendió.',
            self::CarritoRecuperarSinForzarCentro => 'Recuperar desde un documento manteniendo sus centros.',
            self::CuponesUsar => 'Ver y aplicar cupones.',
            self::EnvioBonificar => 'Bonificar gastos de envío y embalaje.',
            self::CarritoAgregar => 'Agregar productos al carrito desde el catálogo y el detalle.',
            self::CotizacionGuardarEnCualquierPaso => 'Los demás solo guardan en el paso 2.',
            self::CotizacionCrear => 'Guardar o enviar una cotización u oferta común desde el carrito.',
            self::CotizacionCrearEspecial => 'Agregar productos a medida (MVSE), que convierten el carrito en una oferta especial.',
            self::PedidoEmitir => 'Emitir el pedido desde el carrito. Hoy el responsable de cuenta no puede.',
            self::PedidoExigirMailConfirmacion => 'Pide elegir el mail al que se envía la confirmación.',
            self::PedidoFinalidad => 'Cargar la finalidad del pedido.',
            self::PedidoConsignacion => 'Marcar el pedido en consignación (Argentina).',
            self::PedidoPagoMostrador => 'Pedido de mostrador: abona en caja, solo cuenta corriente.',
            self::PedidoOfrecerRetiroMostrador => 'Ofrecer el retiro por mostrador.',
            self::PagoCondicionesAdicionales => 'Anticipo, otras condiciones y cambiar la condición del documento.',
            self::PagoCambiarMoneda => 'Hoy es Desarrollador y dos mails hardcodeados, que pasan a permiso directo.',
            self::PedidoVerMuestrasGratis => 'Ver y abrir pedidos de muestra gratis.',
            self::PedidoVerAvisoPago => 'Avisos de pago que se muestran solo a clientes al confirmar.',
            self::DocumentoElegirPosiciones => 'Elegir qué posiciones pasar al carrito.',
            self::DocumentoCopiarCotizacion => 'Copiar y dar de alta por parecido.',
            self::DocumentoActualizarOfertaEspecial => 'Actualizar una oferta especial ya vencida.',
            self::DocumentoOmitirControlCentro => 'No exige que coincidan los centros al comprar, modificar o recotizar.',
            self::DocumentoVerCondicionesInternas => 'Sucursal de suministro y notas internas del documento.',
            self::MiCuentaCompras => 'Las secciones Compras y Transacciones.',
            self::MiCuentaVentas => 'La sección Ventas del proveedor.',
            self::MiCuentaAyuda => 'La sección Ayuda.',
            self::MiCuentaCentroAyuda => 'Consultas y reclamos.',
            self::MiCuentaEstadoCuenta => 'El estado de cuenta.',
            self::MiCuentaLegajoImpositivo => 'El legajo impositivo (Argentina).',
            self::MiCuentaMisCodigos => 'Códigos propios del cliente para los productos.',
            self::MiCuentaDirecciones => 'Direcciones de entrega.',
            self::MiCuentaCambiarContrasena => 'Cambiar la contraseña desde Mi cuenta.',
            self::PersonasGestionar => 'Gestionar las personas de la cuenta.',
            self::PersonasFavoritas => 'Marcar personas favoritas y ver a quién están asociadas.',
            self::ComprobantesPagoVer => 'Consultar comprobantes de pago.',
            self::ReclamosModoAsesor => 'Ver todos los mensajes, chat privado, elegir cliente y figurar como creador.',
            self::ReclamosNotasInternas => 'Cargar notas internas en un reclamo.',
            self::CrmGestionarContactos => 'Crear, asociar, actualizar y cerrar contactos de clientes.',
            self::KonnenBusqueda => 'Filtros y subfamilias del canal Konnen.',
            self::KonnenDocumentos => 'Opera solo documentos Konnen; se informa como Konnen a SAP; login por documento M/K.',
            self::CuentaClienteUsar => 'Se identifica como cliente ante SAP y en el registro.',
            self::CuentaProveedorUsar => 'Datos de proveedor e ingreso como proveedor.',
            self::ProveedoresPortal => 'Órdenes de compra y facturas.',
            self::ProveedorOperarComo => 'Elegir un proveedor y trabajar por él (Cuentas a pagar).',
            self::PedidosBloqueadosFiltrarPorAsesor => 'El filtro Asesor en el seguimiento de pedidos bloqueados.',
            self::TransportesVerHorarios => 'La columna de horarios en transportes.',
            self::TransportesCrear => 'Dar de alta un transporte nuevo.',
            self::SistemaLogSap => 'Guarda el detalle de las llamadas a SAP del usuario.',
            self::SistemaDebugCarrito => 'La herramienta de debug del carrito.',
            self::SistemaMarcasDesarrollo => 'Marcas técnicas en algunas pantallas.',
            self::SistemaNoInformarUsuarioSap => 'No envía el usuario web a SAP al consultar clientes.',
            self::TotemGenerarTicket => 'Generar un ticket de prueba del tótem (NemoQ).',
            self::TotemVerTicketsEnEspera => 'Consultar los tickets en espera del tótem (NemoQ).',
            self::ProductoMantenimiento => 'Actualizar un material desde SAP y regenerar el Excel de materiales.',
            self::GestionIngresar => 'Entrar a gestión.',
            self::RolesAdministrar => 'Las pantallas de roles y permisos.',
            self::UsuariosAdministrarInternos => 'Sin este permiso solo se gestionan proveedores.',
            self::UserIndex => 'Listado de usuarios',
            self::UserCreate => 'Crear usuario',
            self::UserEdit => 'Editar usuario',
            self::UserDelete => 'Eliminar usuario',
            self::ProductIndex => 'Listado de Productos',
            self::PaymentIndex => 'Listado de Pagos',
            self::ClientCodeIndex => 'Listado de Código Cliente',
            self::ClientCodeCreate => 'Crear Código Cliente',
            self::ClientCodeDestroy => 'Eliminar Código Cliente',
            self::ListIndex => 'Listado de Listas',
            self::ListShow => 'Listas de Empresa',
            self::ListCreate => 'Crear Mis Listas',
            self::ListDestroy => 'Eliminar Lista',
            self::LegajoIndex => 'Listado del legajo impositivo',
            self::LegajoUpdate => 'Editar el legajo impositivo',
            self::MaterialsIndex => 'Listado de Materiales con Defectos',
            self::MaterialsShow => 'Ver detalle de Material con Defecto',
            self::MaterialsCreate => 'Crear Material con Defecto',
            self::MaterialsDestroy => 'Eliminar Material con Defecto',
            self::LeadIndex => 'Listado de Leads',
            self::TagIndex => 'Listado de Etiquetas',
            self::TagCreate => 'Crear Etiqueta',
            self::TagEdit => 'Editar Etiqueta',
            self::TagDestroy => 'Eliminar Etiqueta',
            self::FilterOrderIndex => 'Listado de Filtros',
            self::FilterOrderShow => 'Ver Ordenamiento de filtros',
            self::FilterOrderUpdate => 'Cambiar el orden de los filtros',
            self::ComponentTypesTypes => 'Listado de Tipos de componentes',
            self::ComponentTypesIndex => 'Listado de los Componentes de la sección',
            self::ComponentsIndex => 'Listado de Componentes',
            self::ComponentsCreate => 'Crear Componente',
            self::ComponentsComponentEdit => 'Editar Componente',
            self::ComponentsComponentDelete => 'Eliminar Componente',
            self::LogosIndex => 'Listado de Logos',
            self::LogosCreate => 'Crear Logo',
            self::LogosLogoEdit => 'Editar Logo',
            self::LogosLogoDelete => 'Eliminar Logo',
            self::HierarchyNodeIndex => 'Listado de Nodos',
            self::HierarchyNodeCreate => 'Crear Nodo',
            self::HierarchyNodeNodeEdit => 'Editar Nodo',
            self::HierarchyNodeNodeDelete => 'Eliminar Nodo',
            self::TeamIndex => 'Listado de Personal',
            self::TeamCreate => 'Crear Personal',
            self::TeamEdit => 'Editar Personal',
            self::TeamDelete => 'Eliminar Personal',
            self::MessagesIndex => 'Listado de Mensajes',
            self::MessagesCreate => 'Crear Mensajes',
            self::MessagesMessageEdit => 'Editar Mensajes',
            self::MessagesMessageDelete => 'Eliminar Mensajes',
            self::NotificationsIndex => 'Listado de Novedades',
            self::NotificationsCreate => 'Crear Novedad',
            self::NotificationsNotificationEdit => 'Editar Novedad',
            self::NotificationsNotificationDelete => 'Eliminar Novedad',
            self::FeatureFlagsIndex => 'Listado de Funcionalidades',
            self::FeatureFlagsCreate => 'Crear funcionalidad',
            self::FeatureFlagsFeatureFlagEdit => 'Editar Funcionalidades',
            self::FeatureFlagsFeatureFlagDelete => 'Eliminar Funcionalidades',
            self::CertificacionIndex => 'Listado de la certificación',
            self::CertificacionUpdate => 'Editar la certificación',
            self::CalidadIndex => 'Listado de la politica de calidad',
            self::CalidadUpdate => 'Editar la politica de calidad',
            self::SegmentsIndex => 'Listado de Segmentos',
            self::SegmentsCreate => 'Crear Segmento',
            self::SegmentsSegmentEdit => 'Editar Segmento',
            self::SegmentsSegmentDelete => 'Eliminar Segmento',
            self::EmpresasIndex => 'Listado de Empresas',
            self::HeaderLinksIndex => 'Listado de Links del header',
            self::HeaderLinksCreate => 'Crear Links del header',
            self::HeaderLinksLinkEdit => 'Editar Links del header',
            self::HeaderLinksLinkDelete => 'Eliminar Links del header',
            self::InfoLibraryIndex => 'La Biblioteca de Información técnica',
            self::InfoLibraryCollectionsIndex => 'Listado de Colecciones',
            self::InfoLibraryCollectionsCreate => 'Crear Colección',
            self::InfoLibraryCollectionsCollectionEdit => 'Editar Colección',
            self::InfoLibraryCollectionsCollectionDelete => 'Eliminar Colección',
            self::InfoLibraryArticlesIndex => 'Listado de Artículos',
            self::InfoLibraryArticlesCreate => 'Crear Artículo',
            self::InfoLibraryArticlesArticleEdit => 'Editar Artículo',
            self::InfoLibraryArticlesArticleDelete => 'Eliminar Artículo',
            self::InfoFactsIndex => 'Listado de datos curiosos',
            self::InfoFactsCreate => 'Crear dato curioso',
            self::InfoFactsFactEdit => 'Editar dato curioso',
            self::InfoFactsFactDelete => 'Eliminar dato curioso',
            self::FooterIndex => 'Ver el footer',
            self::FooterEdit => 'Editar logo, redes, columnas y marcas del footer',
        };
    }

    /** Módulo: 'pin' o 'gestion'. Se guarda en permissions.type. */
    public function modulo(): string
    {
        return match ($this) {
            self::PinIngresar => 'pin',
            self::MiCuentaIngresar => 'pin',
            self::MisGestionesIngresar => 'pin',
            self::ClienteElegirObligatorio => 'pin',
            self::ChatAyudaVer => 'pin',
            self::EncuestaResponder => 'pin',
            self::ClienteOperarComo => 'pin',
            self::CatalogoVerComoVendedor => 'pin',
            self::ClienteDarDeAlta => 'pin',
            self::ClienteVerInformacionInterna => 'pin',
            self::ClienteVerNotas => 'pin',
            self::VendedorIdSap => 'pin',
            self::ProductosEspecialesVer => 'pin',
            self::PrecioVerStandard => 'pin',
            self::ProductoVerMarcasInternas => 'pin',
            self::ProductoVerDescuentoMaximo => 'pin',
            self::StockVerPorSucursal => 'pin',
            self::CatalogoVerDatosTecnicos => 'pin',
            self::RecortesVerDepositoOrigen => 'pin',
            self::PoliticaPreciosDescargar => 'pin',
            self::ProductoVerPrecioSinDescuento => 'pin',
            self::CatalogoVerComoComprar => 'pin',
            self::ListasUsar => 'pin',
            self::ListasCrearFamiq => 'pin',
            self::ListasEditarFamiq => 'pin',
            self::ListasDescargarReporte => 'pin',
            self::CarritoPrecioManual => 'pin',
            self::CarritoNotas => 'pin',
            self::CarritoAlternativas => 'pin',
            self::CarritoOpcionesCabecera => 'pin',
            self::CarritoCargaMasivaOfertaPrecioManual => 'pin',
            self::CarritoCambiarCentro => 'pin',
            self::CarritoAnularConMotivo => 'pin',
            self::CarritoVendedorReferenciado => 'pin',
            self::CarritoVendedorReferenciadoKiosco => 'pin',
            self::CarritoRecuperarSinForzarCentro => 'pin',
            self::CuponesUsar => 'pin',
            self::EnvioBonificar => 'pin',
            self::CarritoAgregar => 'pin',
            self::CotizacionGuardarEnCualquierPaso => 'pin',
            self::CotizacionCrear => 'pin',
            self::CotizacionCrearEspecial => 'pin',
            self::PedidoEmitir => 'pin',
            self::PedidoExigirMailConfirmacion => 'pin',
            self::PedidoFinalidad => 'pin',
            self::PedidoConsignacion => 'pin',
            self::PedidoPagoMostrador => 'pin',
            self::PedidoOfrecerRetiroMostrador => 'pin',
            self::PagoCondicionesAdicionales => 'pin',
            self::PagoCambiarMoneda => 'pin',
            self::PedidoVerMuestrasGratis => 'pin',
            self::PedidoVerAvisoPago => 'pin',
            self::DocumentoElegirPosiciones => 'pin',
            self::DocumentoCopiarCotizacion => 'pin',
            self::DocumentoActualizarOfertaEspecial => 'pin',
            self::DocumentoOmitirControlCentro => 'pin',
            self::DocumentoVerCondicionesInternas => 'pin',
            self::MiCuentaCompras => 'pin',
            self::MiCuentaVentas => 'pin',
            self::MiCuentaAyuda => 'pin',
            self::MiCuentaCentroAyuda => 'pin',
            self::MiCuentaEstadoCuenta => 'pin',
            self::MiCuentaLegajoImpositivo => 'pin',
            self::MiCuentaMisCodigos => 'pin',
            self::MiCuentaDirecciones => 'pin',
            self::MiCuentaCambiarContrasena => 'pin',
            self::PersonasGestionar => 'pin',
            self::PersonasFavoritas => 'pin',
            self::ComprobantesPagoVer => 'pin',
            self::ReclamosModoAsesor => 'pin',
            self::ReclamosNotasInternas => 'pin',
            self::CrmGestionarContactos => 'pin',
            self::KonnenBusqueda => 'pin',
            self::KonnenDocumentos => 'pin',
            self::CuentaClienteUsar => 'pin',
            self::CuentaProveedorUsar => 'pin',
            self::ProveedoresPortal => 'pin',
            self::ProveedorOperarComo => 'pin',
            self::PedidosBloqueadosFiltrarPorAsesor => 'pin',
            self::TransportesVerHorarios => 'pin',
            self::TransportesCrear => 'pin',
            self::SistemaLogSap => 'pin',
            self::SistemaDebugCarrito => 'pin',
            self::SistemaMarcasDesarrollo => 'pin',
            self::SistemaNoInformarUsuarioSap => 'pin',
            self::TotemGenerarTicket => 'pin',
            self::TotemVerTicketsEnEspera => 'pin',
            self::ProductoMantenimiento => 'pin',
            self::GestionIngresar => 'gestion',
            self::RolesAdministrar => 'gestion',
            self::UsuariosAdministrarInternos => 'gestion',
            self::UserIndex => 'gestion',
            self::UserCreate => 'gestion',
            self::UserEdit => 'gestion',
            self::UserDelete => 'gestion',
            self::ProductIndex => 'gestion',
            self::PaymentIndex => 'gestion',
            self::ClientCodeIndex => 'gestion',
            self::ClientCodeCreate => 'gestion',
            self::ClientCodeDestroy => 'gestion',
            self::ListIndex => 'gestion',
            self::ListShow => 'gestion',
            self::ListCreate => 'gestion',
            self::ListDestroy => 'gestion',
            self::LegajoIndex => 'gestion',
            self::LegajoUpdate => 'gestion',
            self::MaterialsIndex => 'gestion',
            self::MaterialsShow => 'gestion',
            self::MaterialsCreate => 'gestion',
            self::MaterialsDestroy => 'gestion',
            self::LeadIndex => 'gestion',
            self::TagIndex => 'gestion',
            self::TagCreate => 'gestion',
            self::TagEdit => 'gestion',
            self::TagDestroy => 'gestion',
            self::FilterOrderIndex => 'gestion',
            self::FilterOrderShow => 'gestion',
            self::FilterOrderUpdate => 'gestion',
            self::ComponentTypesTypes => 'gestion',
            self::ComponentTypesIndex => 'gestion',
            self::ComponentsIndex => 'gestion',
            self::ComponentsCreate => 'gestion',
            self::ComponentsComponentEdit => 'gestion',
            self::ComponentsComponentDelete => 'gestion',
            self::LogosIndex => 'gestion',
            self::LogosCreate => 'gestion',
            self::LogosLogoEdit => 'gestion',
            self::LogosLogoDelete => 'gestion',
            self::HierarchyNodeIndex => 'gestion',
            self::HierarchyNodeCreate => 'gestion',
            self::HierarchyNodeNodeEdit => 'gestion',
            self::HierarchyNodeNodeDelete => 'gestion',
            self::TeamIndex => 'gestion',
            self::TeamCreate => 'gestion',
            self::TeamEdit => 'gestion',
            self::TeamDelete => 'gestion',
            self::MessagesIndex => 'gestion',
            self::MessagesCreate => 'gestion',
            self::MessagesMessageEdit => 'gestion',
            self::MessagesMessageDelete => 'gestion',
            self::NotificationsIndex => 'gestion',
            self::NotificationsCreate => 'gestion',
            self::NotificationsNotificationEdit => 'gestion',
            self::NotificationsNotificationDelete => 'gestion',
            self::FeatureFlagsIndex => 'gestion',
            self::FeatureFlagsCreate => 'gestion',
            self::FeatureFlagsFeatureFlagEdit => 'gestion',
            self::FeatureFlagsFeatureFlagDelete => 'gestion',
            self::CertificacionIndex => 'gestion',
            self::CertificacionUpdate => 'gestion',
            self::CalidadIndex => 'gestion',
            self::CalidadUpdate => 'gestion',
            self::SegmentsIndex => 'gestion',
            self::SegmentsCreate => 'gestion',
            self::SegmentsSegmentEdit => 'gestion',
            self::SegmentsSegmentDelete => 'gestion',
            self::EmpresasIndex => 'gestion',
            self::HeaderLinksIndex => 'gestion',
            self::HeaderLinksCreate => 'gestion',
            self::HeaderLinksLinkEdit => 'gestion',
            self::HeaderLinksLinkDelete => 'gestion',
            self::InfoLibraryIndex => 'gestion',
            self::InfoLibraryCollectionsIndex => 'gestion',
            self::InfoLibraryCollectionsCreate => 'gestion',
            self::InfoLibraryCollectionsCollectionEdit => 'gestion',
            self::InfoLibraryCollectionsCollectionDelete => 'gestion',
            self::InfoLibraryArticlesIndex => 'gestion',
            self::InfoLibraryArticlesCreate => 'gestion',
            self::InfoLibraryArticlesArticleEdit => 'gestion',
            self::InfoLibraryArticlesArticleDelete => 'gestion',
            self::InfoFactsIndex => 'gestion',
            self::InfoFactsCreate => 'gestion',
            self::InfoFactsFactEdit => 'gestion',
            self::InfoFactsFactDelete => 'gestion',
            self::FooterIndex => 'gestion',
            self::FooterEdit => 'gestion',
        };
    }

    /** Agrupador para mostrar el catálogo. */
    public function grupo(): string
    {
        return match ($this) {
            self::PinIngresar => 'Ingreso y navegación',
            self::MiCuentaIngresar => 'Ingreso y navegación',
            self::MisGestionesIngresar => 'Ingreso y navegación',
            self::ClienteElegirObligatorio => 'Ingreso y navegación',
            self::ChatAyudaVer => 'Ingreso y navegación',
            self::EncuestaResponder => 'Ingreso y navegación',
            self::ClienteOperarComo => 'Operar en nombre de clientes',
            self::CatalogoVerComoVendedor => 'Operar en nombre de clientes',
            self::ClienteDarDeAlta => 'Operar en nombre de clientes',
            self::ClienteVerInformacionInterna => 'Operar en nombre de clientes',
            self::ClienteVerNotas => 'Operar en nombre de clientes',
            self::VendedorIdSap => 'Operar en nombre de clientes',
            self::ProductosEspecialesVer => 'Catálogo y producto',
            self::PrecioVerStandard => 'Catálogo y producto',
            self::ProductoVerMarcasInternas => 'Catálogo y producto',
            self::ProductoVerDescuentoMaximo => 'Catálogo y producto',
            self::StockVerPorSucursal => 'Catálogo y producto',
            self::CatalogoVerDatosTecnicos => 'Catálogo y producto',
            self::RecortesVerDepositoOrigen => 'Catálogo y producto',
            self::PoliticaPreciosDescargar => 'Catálogo y producto',
            self::ProductoVerPrecioSinDescuento => 'Catálogo y producto',
            self::CatalogoVerComoComprar => 'Catálogo y producto',
            self::ListasUsar => 'Listas y favoritos',
            self::ListasCrearFamiq => 'Listas y favoritos',
            self::ListasEditarFamiq => 'Listas y favoritos',
            self::ListasDescargarReporte => 'Listas y favoritos',
            self::CarritoPrecioManual => 'Carrito',
            self::CarritoNotas => 'Carrito',
            self::CarritoAlternativas => 'Carrito',
            self::CarritoOpcionesCabecera => 'Carrito',
            self::CarritoCargaMasivaOfertaPrecioManual => 'Carrito',
            self::CarritoCambiarCentro => 'Carrito',
            self::CarritoAnularConMotivo => 'Carrito',
            self::CarritoVendedorReferenciado => 'Carrito',
            self::CarritoVendedorReferenciadoKiosco => 'Carrito',
            self::CarritoRecuperarSinForzarCentro => 'Carrito',
            self::CuponesUsar => 'Carrito',
            self::EnvioBonificar => 'Carrito',
            self::CarritoAgregar => 'Carrito',
            self::CotizacionGuardarEnCualquierPaso => 'Cotizaciones y pedidos',
            self::CotizacionCrear => 'Cotizaciones y pedidos',
            self::CotizacionCrearEspecial => 'Cotizaciones y pedidos',
            self::PedidoEmitir => 'Cotizaciones y pedidos',
            self::PedidoExigirMailConfirmacion => 'Cotizaciones y pedidos',
            self::PedidoFinalidad => 'Cotizaciones y pedidos',
            self::PedidoConsignacion => 'Cotizaciones y pedidos',
            self::PedidoPagoMostrador => 'Cotizaciones y pedidos',
            self::PedidoOfrecerRetiroMostrador => 'Cotizaciones y pedidos',
            self::PagoCondicionesAdicionales => 'Cotizaciones y pedidos',
            self::PagoCambiarMoneda => 'Cotizaciones y pedidos',
            self::PedidoVerMuestrasGratis => 'Cotizaciones y pedidos',
            self::PedidoVerAvisoPago => 'Cotizaciones y pedidos',
            self::DocumentoElegirPosiciones => 'Documentos',
            self::DocumentoCopiarCotizacion => 'Documentos',
            self::DocumentoActualizarOfertaEspecial => 'Documentos',
            self::DocumentoOmitirControlCentro => 'Documentos',
            self::DocumentoVerCondicionesInternas => 'Documentos',
            self::MiCuentaCompras => 'Mi cuenta',
            self::MiCuentaVentas => 'Mi cuenta',
            self::MiCuentaAyuda => 'Mi cuenta',
            self::MiCuentaCentroAyuda => 'Mi cuenta',
            self::MiCuentaEstadoCuenta => 'Mi cuenta',
            self::MiCuentaLegajoImpositivo => 'Mi cuenta',
            self::MiCuentaMisCodigos => 'Mi cuenta',
            self::MiCuentaDirecciones => 'Mi cuenta',
            self::MiCuentaCambiarContrasena => 'Mi cuenta',
            self::PersonasGestionar => 'Mi cuenta',
            self::PersonasFavoritas => 'Mi cuenta',
            self::ComprobantesPagoVer => 'Mi cuenta',
            self::ReclamosModoAsesor => 'Reclamos',
            self::ReclamosNotasInternas => 'Reclamos',
            self::CrmGestionarContactos => 'Reclamos',
            self::KonnenBusqueda => 'Canal Konnen',
            self::KonnenDocumentos => 'Canal Konnen',
            self::CuentaClienteUsar => 'Clientes y proveedores',
            self::CuentaProveedorUsar => 'Clientes y proveedores',
            self::ProveedoresPortal => 'Clientes y proveedores',
            self::ProveedorOperarComo => 'Clientes y proveedores',
            self::PedidosBloqueadosFiltrarPorAsesor => 'Pedidos bloqueados y transportes',
            self::TransportesVerHorarios => 'Pedidos bloqueados y transportes',
            self::TransportesCrear => 'Pedidos bloqueados y transportes',
            self::SistemaLogSap => 'Sistema',
            self::SistemaDebugCarrito => 'Sistema',
            self::SistemaMarcasDesarrollo => 'Sistema',
            self::SistemaNoInformarUsuarioSap => 'Sistema',
            self::TotemGenerarTicket => 'Sistema',
            self::TotemVerTicketsEnEspera => 'Sistema',
            self::ProductoMantenimiento => 'Sistema',
            self::GestionIngresar => 'Gestión',
            self::RolesAdministrar => 'Gestión',
            self::UsuariosAdministrarInternos => 'Gestión',
            self::UserIndex => 'Pantallas de gestión',
            self::UserCreate => 'Pantallas de gestión',
            self::UserEdit => 'Pantallas de gestión',
            self::UserDelete => 'Pantallas de gestión',
            self::ProductIndex => 'Pantallas de gestión',
            self::PaymentIndex => 'Pantallas de gestión',
            self::ClientCodeIndex => 'Pantallas de gestión',
            self::ClientCodeCreate => 'Pantallas de gestión',
            self::ClientCodeDestroy => 'Pantallas de gestión',
            self::ListIndex => 'Pantallas de gestión',
            self::ListShow => 'Pantallas de gestión',
            self::ListCreate => 'Pantallas de gestión',
            self::ListDestroy => 'Pantallas de gestión',
            self::LegajoIndex => 'Pantallas de gestión',
            self::LegajoUpdate => 'Pantallas de gestión',
            self::MaterialsIndex => 'Pantallas de gestión',
            self::MaterialsShow => 'Pantallas de gestión',
            self::MaterialsCreate => 'Pantallas de gestión',
            self::MaterialsDestroy => 'Pantallas de gestión',
            self::LeadIndex => 'Pantallas de gestión',
            self::TagIndex => 'Pantallas de gestión',
            self::TagCreate => 'Pantallas de gestión',
            self::TagEdit => 'Pantallas de gestión',
            self::TagDestroy => 'Pantallas de gestión',
            self::FilterOrderIndex => 'Pantallas de gestión',
            self::FilterOrderShow => 'Pantallas de gestión',
            self::FilterOrderUpdate => 'Pantallas de gestión',
            self::ComponentTypesTypes => 'Pantallas de gestión',
            self::ComponentTypesIndex => 'Pantallas de gestión',
            self::ComponentsIndex => 'Pantallas de gestión',
            self::ComponentsCreate => 'Pantallas de gestión',
            self::ComponentsComponentEdit => 'Pantallas de gestión',
            self::ComponentsComponentDelete => 'Pantallas de gestión',
            self::LogosIndex => 'Pantallas de gestión',
            self::LogosCreate => 'Pantallas de gestión',
            self::LogosLogoEdit => 'Pantallas de gestión',
            self::LogosLogoDelete => 'Pantallas de gestión',
            self::HierarchyNodeIndex => 'Pantallas de gestión',
            self::HierarchyNodeCreate => 'Pantallas de gestión',
            self::HierarchyNodeNodeEdit => 'Pantallas de gestión',
            self::HierarchyNodeNodeDelete => 'Pantallas de gestión',
            self::TeamIndex => 'Pantallas de gestión',
            self::TeamCreate => 'Pantallas de gestión',
            self::TeamEdit => 'Pantallas de gestión',
            self::TeamDelete => 'Pantallas de gestión',
            self::MessagesIndex => 'Pantallas de gestión',
            self::MessagesCreate => 'Pantallas de gestión',
            self::MessagesMessageEdit => 'Pantallas de gestión',
            self::MessagesMessageDelete => 'Pantallas de gestión',
            self::NotificationsIndex => 'Pantallas de gestión',
            self::NotificationsCreate => 'Pantallas de gestión',
            self::NotificationsNotificationEdit => 'Pantallas de gestión',
            self::NotificationsNotificationDelete => 'Pantallas de gestión',
            self::FeatureFlagsIndex => 'Pantallas de gestión',
            self::FeatureFlagsCreate => 'Pantallas de gestión',
            self::FeatureFlagsFeatureFlagEdit => 'Pantallas de gestión',
            self::FeatureFlagsFeatureFlagDelete => 'Pantallas de gestión',
            self::CertificacionIndex => 'Pantallas de gestión',
            self::CertificacionUpdate => 'Pantallas de gestión',
            self::CalidadIndex => 'Pantallas de gestión',
            self::CalidadUpdate => 'Pantallas de gestión',
            self::SegmentsIndex => 'Pantallas de gestión',
            self::SegmentsCreate => 'Pantallas de gestión',
            self::SegmentsSegmentEdit => 'Pantallas de gestión',
            self::SegmentsSegmentDelete => 'Pantallas de gestión',
            self::EmpresasIndex => 'Pantallas de gestión',
            self::HeaderLinksIndex => 'Pantallas de gestión',
            self::HeaderLinksCreate => 'Pantallas de gestión',
            self::HeaderLinksLinkEdit => 'Pantallas de gestión',
            self::HeaderLinksLinkDelete => 'Pantallas de gestión',
            self::InfoLibraryIndex => 'Pantallas de gestión',
            self::InfoLibraryCollectionsIndex => 'Pantallas de gestión',
            self::InfoLibraryCollectionsCreate => 'Pantallas de gestión',
            self::InfoLibraryCollectionsCollectionEdit => 'Pantallas de gestión',
            self::InfoLibraryCollectionsCollectionDelete => 'Pantallas de gestión',
            self::InfoLibraryArticlesIndex => 'Pantallas de gestión',
            self::InfoLibraryArticlesCreate => 'Pantallas de gestión',
            self::InfoLibraryArticlesArticleEdit => 'Pantallas de gestión',
            self::InfoLibraryArticlesArticleDelete => 'Pantallas de gestión',
            self::InfoFactsIndex => 'Pantallas de gestión',
            self::InfoFactsCreate => 'Pantallas de gestión',
            self::InfoFactsFactEdit => 'Pantallas de gestión',
            self::InfoFactsFactDelete => 'Pantallas de gestión',
            self::FooterIndex => 'Pantallas de gestión',
            self::FooterEdit => 'Pantallas de gestión',
        };
    }
}
